/* Optional challenges have their own local state. They never change attendance or main-game saves. */
(function(root){
'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,action,cls='wide')=>{const b=el('button',text,cls);b.type='button';b.addEventListener('click',action);return b;};
class BonusUI{
constructor(options){this.o=options;this.engine=root.RPGBonus;this.content=root.RPGBonusContent;this.state=this.engine.createState();this.profileKey=null;this.readOnly=false;this.summaryCache=new Map();}
ensure(){const profile=this.o.getProfile();if(!profile)return false;const key=(this.engine.STORAGE_KEY||'ndmu-ethics-rpg:bonus:v1')+':'+profile.createdAt;if(key===this.profileKey)return true;this.profileKey=key;this.readOnly=false;this.summaryCache.clear();this.state=this.engine.createState();try{const raw=this.o.storage?.getItem(key);if(raw){const parsed=JSON.parse(raw);this.engine.validateState(parsed);this.state=parsed;}}catch(error){this.readOnly=true;this.o.toast('支線備份無法讀取；原資料保留，主線仍可繼續。');}return true;}
chapter(){return this.content.getChapter(this.o.getChapter().id);}
summary(chapterId=this.o.getChapter().id){this.ensure();if(!this.summaryCache.has(chapterId))this.summaryCache.set(chapterId,this.engine.getSummary(this.state,chapterId));return this.summaryCache.get(chapterId);}
apply(result){if(!result.ok){this.o.toast(result.feedback?.text||'此操作尚無法完成。');return false;}this.state=result.state;if(result.changed)this.summaryCache.clear();if(result.changed&&!this.readOnly){try{this.o.storage?.setItem(this.profileKey,JSON.stringify(this.state));}catch(_){this.o.toast('支線暫存在記憶體；請在探索手冊匯出備份。');}}this.o.onUpdate?.();if(result.awarded?.points||result.correct)this.o.effect?.('discovery');return true;}
markers(){if(!this.ensure())return[];const c=this.o.getChapter(),data=this.content.getChapter(c.id),summary=this.summary(c.id),spots=c.map.bonusSpots?Object.values(c.map.bonusSpots):[{x:3,y:17},{x:13,y:14},{x:6,y:10},{x:10,y:5}],used=new Set();return(data.markers||[]).map((m,i)=>{const preferred=c.map.bonusSpots?.[m.suggestedZone],spot=[preferred,...spots].find(p=>p&&!used.has(p.x+','+p.y))||spots[i%spots.length];used.add(spot.x+','+spot.y);return{...m,...spot,bonus:true,done:summary.completedIds.includes(m.id)||(m.puzzleId&&summary.progress[m.puzzleId]?.solved)};});}
open(){if(!this.ensure())return this.o.toast('先建立學員暱稱，再展開支線探索。');const c=this.o.getChapter(),data=this.content.getChapter(c.id),summary=this.summary(c.id),nodes=[el('p',`${c.region} · ${c.title}`,'muted'),el('p','主線之外，還有散落的故事與小挑戰。這些內容自由參加，不影響通關、反思或出席條件。'),this.stats(summary)];const grid=el('div',undefined,'bonus-grid');for(const m of data.markers||[]){const progress=m.puzzleId?summary.progress[m.puzzleId]:null,visited=summary.visitedIds.includes(m.id),card=el('section',undefined,'bonus-card');card.append(el('span',m.kind==='easterEgg'?'隱藏收藏':'支線挑戰','eyebrow'),el('h3',m.kind==='easterEgg'&&!visited?'一個尚未發現的小祕密':m.name),el('p',visited?m.description:m.kind==='easterEgg'?'留意地圖上閃爍的菱形標記。':m.description));if(m.kind!=='easterEgg'||visited)card.append(button(m.kind==='easterEgg'?'回顧收藏':progress?.solved?'回顧挑戰':visited?'繼續挑戰':'閱讀線索',()=>this.openMarker(m.id),'gold-button wide'));const marker=this.markers().find(x=>x.id===m.id);if(this.o.getState().phase==='exploration'&&marker)card.append(button('前往地點 →',()=>{this.o.close();this.o.routeTo(marker);},'text-button wide'));card.append(el('small',progress?.solved?'已解鎖獎勵':visited&&m.kind==='easterEgg'?'已收藏':m.reward.label,'muted'));grid.append(card);}nodes.push(grid,button('查看個人紀錄榜',()=>this.boards(),'wide'),button('備份支線與收藏 JSON',()=>this.backup(),'text-button wide'));this.o.show('探索手冊',nodes,'SIDE STORIES');}
stats(s){const r=el('div',undefined,'bonus-stats');for(const [value,label]of[[`${s.completed}/${s.total}`,'支線完成'],[`${s.collections}/${s.maxCollections}`,'收藏'],[`${s.puzzles}/${s.maxPuzzles}`,'解謎']]){const item=el('div');item.append(el('strong',value),el('span',label));r.append(item);}return r;}
openMarker(id){if(!this.ensure())return;const c=this.o.getChapter(),m=this.content.getChapter(c.id).markers.find(x=>x.id===id);if(!m)return;const result=this.engine.interact(this.state,c.id,id);if(!this.apply(result))return;const nodes=[el('p',m.story,'bonus-story')];if(result.feedback.text!==m.story)nodes.push(el('p',result.feedback.text,'bonus-feedback'));if(m.puzzleId)nodes.push(button('展開挑戰 →',()=>this.puzzle(m.puzzleId),'gold-button wide'));else nodes.push(el('p',m.reward.label,'badge'));nodes.push(button('返回探索手冊',()=>this.open(),'text-button wide'));this.o.show(m.name,nodes,m.kind==='easterEgg'?'HIDDEN DISCOVERY':'SIDE STORY');}
puzzle(id,feedback=null,draft=null){const c=this.o.getChapter(),p=this.content.getChapter(c.id).puzzles.find(x=>x.id===id);if(!p)return;const progress=this.summary(c.id).progress[id]||{},initialAnswer=draft??progress.lastAnswer,nodes=[el('p',p.prompt,'lead'),el('p',p.instructions,'muted')],form=el('form',undefined,'bonus-puzzle');form.id='bonus-puzzle-form';let answer;
if(p.kind==='evidence-sort'){const selects={};for(const card of p.cards){const row=el('label',undefined,'bonus-sort-row');row.append(el('span',card.text||card.label));const select=el('select');select.required=true;select.setAttribute('aria-label','分類：'+(card.text||card.label));const empty=el('option','選擇分類');empty.value='';select.append(empty);for(const category of p.categories){const option=el('option',category.label||category.text);option.value=category.id;select.append(option);}select.value=initialAnswer?.[card.id]||'';selects[card.id]=select;row.append(select);form.append(row);}answer=()=>Object.fromEntries(Object.entries(selects).map(([key,select])=>[key,select.value]));}
else if(p.kind==='dependency-order'){const constraints=el('ul',undefined,'bonus-constraints');for(const rule of p.constraints||[])constraints.append(el('li',rule.reason));form.append(constraints);const selects=[];for(let i=0;i<p.cards.length;i++){const row=el('label',undefined,'bonus-sort-row');row.append(el('span',`第 ${i+1} 步`));const select=el('select');select.required=true;select.setAttribute('aria-label',`第 ${i+1} 步驟`);const empty=el('option','選擇步驟');empty.value='';select.append(empty);for(const card of p.cards){const option=el('option',card.text||card.label);option.value=card.id;select.append(option);}select.value=initialAnswer?.[i]||'';selects.push(select);row.append(select);form.append(row);}answer=()=>selects.map(x=>x.value);}
else if(p.kind==='resource-plan'){const choices=[];const budget=el('p',undefined,'bonus-budget');budget.textContent='可用資源：'+Object.entries(p.budget||{}).map(([key,value])=>`${p.budgetLabels?.[key]||key} ${value}`).join(' · ');form.append(budget);if(p.requirements?.length)form.append(el('p','需要兼顧：'+p.requirements.map(r=>r.label).join('、'),'muted'));for(const choice of p.choices){const row=el('label',undefined,'bonus-choice'),check=el('input');check.type='checkbox';check.value=choice.id;check.checked=Array.isArray(initialAnswer)&&initialAnswer.includes(choice.id);choices.push(check);const text=el('span');text.append(el('strong',choice.label||choice.text));if(choice.description)text.append(el('small',choice.description));if(choice.covers?.length)text.append(el('small','可支援：'+choice.covers.map(id=>p.requirements?.find(r=>r.id===id)?.label||id).join('、')));if(choice.cost)text.append(el('small','成本：'+Object.entries(choice.cost).map(([key,value])=>`${p.budgetLabels?.[key]||key} ${value}`).join(' · ')));row.append(check,text);form.append(row);}answer=()=>choices.filter(x=>x.checked).map(x=>x.value);}
else{nodes.push(el('p','這個挑戰尚未提供操作介面。'));this.o.show(p.title,nodes,'OPTIONAL CHALLENGE');return;}
if(feedback){const box=el('section',undefined,'bonus-feedback'+(feedback.correct?' success':''));box.setAttribute('role','status');box.append(el('strong',feedback.feedback.title),el('p',feedback.feedback.text));for(const detail of feedback.feedback.details||[])box.append(el('p',detail));nodes.push(box);}
const submit=el('button',progress.solved?'再次檢查':'檢查我的安排','gold-button wide');submit.type='submit';form.append(submit);form.addEventListener('submit',event=>{event.preventDefault();const currentDraft=answer(),result=this.engine.answer(this.state,c.id,id,currentDraft);const accepted=this.apply(result);this.puzzle(id,result,accepted?null:currentDraft);});nodes.push(form);if(progress.solved&&!feedback?.correct)nodes.push(el('p',p.rationale,'bonus-feedback success'));nodes.push(button('需要一點提示',()=>{const currentDraft=answer(),r=this.engine.hint(this.state,c.id,id);this.apply(r);this.puzzle(id,r,currentDraft);},'wide'),button('返回探索手冊',()=>this.open(),'text-button wide'),el('p','可反覆嘗試。使用提示、答錯或跳過，都不影響主線完成條件。','muted'));this.o.show(p.title,nodes,'OPTIONAL CHALLENGE');}
boards(){this.ensure();const cards=el('div',undefined,'bonus-grid');for(const metric of['exploration','collection','puzzle']){const board=this.engine.getLeaderboard(this.state,metric),card=el('section',undefined,'bonus-card'),list=el('ol',undefined,'bonus-ranking');card.append(el('h3',board.label));for(const row of board.rows.filter(r=>r.score>0)){const li=el('li');li.value=row.rank;li.append(el('span',row.chapterId.slice(1)+' '+row.title),el('strong',String(row.score)+board.unit));list.append(li);}card.append(list.children.length?list:el('p','第一項探索紀錄，等你來留下。','muted'));cards.append(card);}this.o.show('個人紀錄榜',[el('p','這裡比較你自己的十三章探索紀錄。尚未連接班級榜，待完成班級登入設定；目前不顯示其他同學，也不替倫理立場、反思文字或個人品格排名。','muted'),el('p','探索榜以各章完成比例比較；同分並列，不比速度或提示次數。','muted'),cards,button('返回探索手冊',()=>this.open(),'wide')],'PERSONAL RECORDS');}
backup(){const raw=JSON.stringify(this.state,null,2),area=el('textarea',undefined,'backup-text');area.readOnly=true;area.value=raw;area.setAttribute('aria-label','支線收藏 JSON 備份');this.o.show('支線與收藏備份',[el('p','此備份只包含可選挑戰與收藏。主線行動和反思，請另外在「紀錄」備份。'),area,button('選取備份文字',()=>{area.focus();area.select();},'wide'),button('下載支線 JSON',()=>this.o.download('國醫倫理冒險-支線收藏.json',raw,'application/json;charset=utf-8'),'gold-button wide')],'BONUS BACKUP');}
}
root.RPGBonusUI=BonusUI;
})(typeof globalThis!=='undefined'?globalThis:this);
