/* 國醫倫理冒險 UI：只經引擎變更狀態；文字輸入一律以 textContent 顯示。 */
(() => {
  'use strict';
  const $=id=>document.getElementById(id), E=window.RPGEngine, D={...window.RPGData,chapters:window.RPGData.chapters.map(c=>window.RPGMaps?window.RPGMaps.apply(c):c)};
  const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
  const btn=(text,action,className)=>{const b=el('button',text,className);b.type='button';b.addEventListener('click',action);return b;};
  const phases={briefing:'任務簡報',exploration:'探索與查證',planning:'選擇行動方案',tactics:'三回合策略',outcome:'任務後果',review:'簡短回顧',complete:'章節已完成'};
  const regions={academy:'學院整備區',camp:'營區協作區',logistics:'補給與行政區',rescue:'救援演訓區'};
  let storage;try{storage=window.localStorage;}catch(_){storage=null;}
  let taskViewKey='';
  let state,chapter,selection={unitId:null,actionId:null,destination:null},toastTimer,walkTimer=null,routeTimer=null,walking=false,submitting=false;
  const modal=$('modal'), body=$('modal-body');
  const store=new window.RPGStore({storage,chapters:D.chapters,onWarning:warning});
  const world=new window.RPGWorld($('scene'),{party:D.party});world.start();
  const music=new window.RPGMusic({onStatus:renderMusicStatus});
  const bonus=window.RPGBonusUI&&window.RPGBonus&&window.RPGBonusContent?new window.RPGBonusUI({storage,getProfile:()=>store.save,getChapter:()=>chapter,getChapters:()=>D.chapters,getState:()=>state,show,close,toast,routeTo,download,onUpdate:()=>{world.bonusMarkers=bonus.markers();world.draw();updateNearby();},effect:kind=>music.effect(kind)}):null;
  function renderMusicStatus(status){
    const playing=status.playing&&status.volume>0;
    $('music-button').textContent=status.playing?'♫ 關閉音樂':status.enabled?'♫ 播放音樂':'♫ 開啟音樂';
    $('music-button').setAttribute('aria-pressed',String(status.enabled));
    $('music-volume').value=String(Math.round(status.volume*100));
    $('music-volume-value').textContent=Math.round(status.volume*100)+'%';
    $('music-status').textContent=status.playing&&!playing?'音量為 0%，調高即可聽見音樂':status.message;
    const check=$('settings-music-enabled'),range=$('settings-music-volume'),value=$('settings-music-value');
    if(check)check.checked=status.enabled;if(range)range.value=String(Math.round(status.volume*100));if(value)value.textContent=Math.round(status.volume*100)+'%';
  }
  function musicSettings(patch){
    try{
      if(store.save)store.setSettings(patch);
      if(Object.hasOwn(patch,'musicEnabled'))music.setEnabled(patch.musicEnabled);
      if(Object.hasOwn(patch,'musicVolume'))music.setVolume(patch.musicVolume);
      renderMusicStatus(music.getStatus());return true;
    }catch(error){toast(error.message);renderMusicStatus(music.getStatus());return false;}
  }
  function syncMusic(){
    const prefs=store.save?.settings,status=music.getStatus();
    if(prefs){if(status.enabled!==prefs.musicEnabled)music.setEnabled(prefs.musicEnabled);if(status.volume!==prefs.musicVolume)music.setVolume(prefs.musicVolume);}
    music.setScene(state.phase);renderMusicStatus(music.getStatus());
  }
  function warning(message){const w=$('storage-warning');w.hidden=false;w.replaceChildren(el('span',message),btn('匯出目前紀錄',()=>{if(store.save)backupText();}));$('save-status').textContent='存檔需要注意，請立即備份';}
  function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
  function show(title,nodes,kicker='FIELD NOTES'){stopWalking();modal.dataset.kind=kicker==='WELCOME, CADET'?'welcome':kicker==='DISCOVERY'?'discovery':'notes';$('modal-title').textContent=title;$('modal-kicker').textContent=kicker;body.replaceChildren(...(Array.isArray(nodes)?nodes:[nodes]));if(!modal.open)modal.showModal();modal.scrollTop=0;}
  function focusTactics(){const target=selection.unitId?$('destination-select'):document.querySelector('#task-body [data-unit-id]:not(:disabled)');target?.focus({preventScroll:true});}
  function close(){modal.close();if(state.phase==='tactics')focusTactics();else $('scene').focus({preventScroll:true});}
  function ask(title,message,action){show(title,[el('p',message),btn('確認繼續',()=>{close();action();},'gold-button wide'),btn('取消',close,'wide')],'PLEASE CONFIRM');}
  function current(){return store.save?store.getCurrent():state;}
  function done(id){const r=store.save?.records[id];return !!r&&[r.current,...r.attempts].some(s=>s.phase==='complete');}
  function transition(result,{quiet=false,light=false}={}){
    if(!result.ok){if(!quiet)toast(result.message);return false;}
    try{state=store.updateState(result.state);}catch(error){toast(error.message);return false;}
    if(light){world.set(state,chapter);updateNearby();}else render();
    if(!quiet){toast(result.message);music.effect(state.phase==='complete'?'complete':result.event?.type==='clue'?'discovery':'confirm');}return true;
  }
  function selectChapter(id,restart=false){stopWalking();try{state=store.startChapter(id,restart);chapter=D.chapters.find(c=>c.id===id);selection={unitId:null,actionId:null,destination:null};if(modal.open)modal.close();render();$('scene').focus({preventScroll:true});toast(`${String(chapter.number).padStart(2,'0')} · ${chapter.title}`);}catch(error){toast(error.message);}}
  function chapterButton(c){const b=btn('',()=>{if(!store.save){onboarding();return;}selectChapter(c.id);},'chapter-item'+(c.id===chapter.id?' active':'')+(done(c.id)?' done':''));b.setAttribute('aria-label',`第${c.number}章 ${c.title}`);if(c.id===chapter.id)b.setAttribute('aria-current','true');const label=el('span',c.title);label.append(el('small',c.topic));b.append(el('span',String(c.number).padStart(2,'0'),'chapter-index'),label,el('span',done(c.id)?'✓':'›','chapter-check'));return b;}
  function partyCard(p,interactive=false){const acted=state.phase==='tactics'&&state.tactical.used.includes(p.id);const n=interactive?btn('',()=>chooseUnit(p.id),'party-card') : el('div',undefined,'party-card');n.classList.toggle('selected',selection.unitId===p.id);n.classList.toggle('acted',acted);if(interactive){n.disabled=acted;n.setAttribute('aria-label',`${p.name}，${p.role}${acted?'，本回合已行動':''}`);}const canvas=el('canvas');canvas.width=90;canvas.height=100;canvas.setAttribute('aria-hidden','true');window.RPGWorld.portrait(canvas,p.color,null,null,p.id);n.append(canvas,el('strong',p.name),el('small',acted?'本回合已行動':p.role));return n;}
  function partyRow(){const r=el('div',undefined,'modal-party');D.party.forEach(p=>r.append(partyCard(p)));return r;}
  function costText(cost={}){return `時間 −${cost.time||0} · 物資 −${cost.supplies||0} · 負荷 ${(cost.load||0)>=0?'+':''}${cost.load||0}`;}
  function render(){
    document.body.dataset.phase=state.phase;chapter=D.chapters.find(c=>c.id===state.chapterId);const count=store.save?store.completedCount():0;
    $('profile-name').textContent=store.save?.nickname||'新進學員';$('completion-count').textContent=count+' / 13';$('chapter-number').textContent='CHAPTER '+String(chapter.number).padStart(2,'0');$('chapter-title').textContent=chapter.title;$('phase-label').textContent=phases[state.phase];$('scene-badge').textContent=state.phase==='tactics'?'隊伍策略區 · 6 × 8':regions[chapter.region]||chapter.region;
    $('scene-caption').hidden=state.phase==='exploration'||state.phase==='tactics';$('scene-caption').textContent=state.phase==='complete'?'這次冒險完成了。把理由帶往下一章。':state.phase==='briefing'?'新的任務正在等你。':state.phase==='planning'?'選擇方案，也承擔它的代價。':'回頭看，才能走得更穩。';
    $('chapter-list').replaceChildren(...D.chapters.map(chapterButton));$('party-strip').replaceChildren(...D.party.map(p=>partyCard(p,state.phase==='tactics')));
    $('field-controls').hidden=!!state.tactical;$('resources').hidden=!state.tactical;
    if(state.tactical)$('resources').replaceChildren(...[['time','可用時間'],['supplies','剩餘物資'],['load','隊員負荷 / 9']].map(([key,label])=>{const n=el('div',undefined,'resource');n.append(el('span',label),el('strong',String(state.tactical.resources[key])));return n;}));
    $('scene').setAttribute('aria-label',state.tactical?(state.phase==='tactics'?'策略地圖，六欄八列。選隊員，再點目的格；也可使用目的地選單與技能按鈕。':'策略結束的部署地圖，六欄八列。後果與歷次行動顯示於任務卡及日誌。'):'探索地圖。方向鍵或WASD移動，E互動，H提示。');
    world.reducedMotion=!!store.save?.settings.reducedMotion||window.matchMedia('(prefers-reduced-motion: reduce)').matches;document.body.classList.toggle('low-motion',world.reducedMotion);world.awards=count;
    world.bonusMarkers=bonus?.markers()||[];
    world.set(state,chapter,selection,state.phase==='tactics'&&selection.unitId?E.reachable(state,chapter,selection.unitId):[]);
    syncMusic();
    renderTask();renderJournal();updateNearby();
    if(!$('storage-warning').hidden)return;$('save-status').textContent=store.save?'行動已自動保存 · 紀錄只留在此瀏覽器':'建立暱稱後開始保存';
  }
  function renderTask(){const b=$('task-body');b.replaceChildren();$('task-heading').textContent=phases[state.phase];$('task-eyebrow').textContent=state.phase==='tactics'?'TEAM COMMAND':'MISSION NOTES';
    const objective=el('div',chapter.objective,'objective');if(state.phase==='briefing'){const speaker=el('div',undefined,'task-speaker'),portrait=el('canvas'),caption=el('div');portrait.width=90;portrait.height=100;window.RPGWorld.portrait(portrait,null,null,null,'doctor');caption.append(el('strong','以晴 · 督導軍醫'),el('small','任務開始前，聽聽小隊的簡報'),el('div',undefined,'speaker-rule'));speaker.append(portrait,caption);b.append(speaker);}b.append(objective);
    if(state.phase==='briefing'){b.append(el('p',chapter.intro,'lead'),el('p','先找三份線索，再回任務站選方案。策略挑戰每回合可派兩名不同隊員，共三回合。','muted'),btn('出發探索 →',()=>{if(!store.save){onboarding();return;}transition(E.begin(state,chapter));$('scene').focus({preventScroll:true});},'gold-button wide'));}
    if(state.phase==='exploration'){const list=el('ul',undefined,'clue-list');chapter.clues.forEach(c=>{const found=state.clues.includes(c.id),li=el('li',undefined,'clue-item'+(found?' found':''));li.append(el('span',(found?'✓ ':'! ')+c.name),btn(found?'重讀':'路線',()=>found?show(c.name,[el('p',c.text)]):routeTo(c)));list.append(li);});b.append(el('p','找齊三份線索，再回任務站。點「路線」前往，抵達後按互動。','muted'),list,btn(state.clues.length===chapter.clues.length?'前往任務站 →':'查看目前路線',()=>hint(), 'wide'),btn('夥伴支線 '+(state.sideDone?'✓':''),()=>state.sideDone?show(chapter.sideQuest.name,[el('p',chapter.sideQuest.text),el('p',chapter.sideQuest.reward,'badge')]):routeTo(chapter.sideQuest),'text-button wide'));}
    if(state.phase==='planning'){b.append(el('p','兩個方案各有作用與限制。選擇後，透過隊伍指令把方案落實。'));chapter.scenario.paths.forEach(path=>{const card=btn('',()=>{selection={unitId:null,actionId:null,destination:null};if(transition(E.choosePath(state,chapter,path.id))){show('第一回合 · 指揮小隊',[el('p','① 點隊員　② 點目的格　③ 選技能並確認。每名隊員每回合只能行動一次；每回合兩次指令，三回合後查看結果。'),el('p','綠色格子是三步內可到的位置。技能須在目標一格內使用；可直接點技能，先帶入最近可用位置。'),btn('我知道了，開始部署',close,'gold-button wide')],'TACTICAL GUIDE');}},'path-card');card.append(el('strong',path.label),el('span',path.text),el('small',path.tradeoff),el('small',costText(path.cost),'branch-cost'));b.append(card);});}
    if(state.phase==='tactics')renderTactics(b);
    if(['outcome','review','complete'].includes(state.phase))renderOutcome(b);
    const viewKey=chapter.id+':'+state.phase+':'+(selection.unitId||'');if(viewKey!==taskViewKey){b.parentElement.scrollTop=0;taskViewKey=viewKey;}
  }
  function chooseUnit(id){if(state.phase!=='tactics'||state.tactical.used.includes(id))return;selection={unitId:id,actionId:null,destination:null};render();focusTactics();}
  function command(){return {token:state.revision,unitId:selection.unitId,actionId:selection.actionId,x:selection.destination?.x,y:selection.destination?.y};}
  function chooseAction(action){selection.actionId=action.id;const target=chapter.scenario.targets.find(t=>t.id===action.targetId);const candidates=E.reachable(state,chapter,selection.unitId).filter(t=>Math.abs(t.x-target.x)+Math.abs(t.y-target.y)<=1).sort((a,b)=>a.distance-b.distance||a.y-b.y||a.x-b.x);
    if(!selection.destination||!E.preview(state,chapter,command()).ok)selection.destination=candidates.length?{x:candidates[0].x,y:candidates[0].y}:null;render();document.querySelector(`[data-action-id="${action.id}"]`)?.focus({preventScroll:true});}
  function renderTactics(b){const t=state.tactical,path=chapter.scenario.paths.find(p=>p.id===state.pathId);b.append(el('p',`第 ${t.round} / 3 回合 · 還有 ${t.commandsLeft} 次指令`,'lead'),el('p',`採用方案：${path.label}`,'muted'));const needs=path.requiredFlags.map(flag=>{const a=chapter.scenario.actions.find(a=>a.flag===flag);return (t.flags.includes(flag)?'✓ ':'○ ')+(a?.label||flag);});b.append(el('p','方案需要：'+needs.join('、'),'muted'));
    if(!selection.unitId){b.append(el('p','先選一名隊員，再選擇位置和技能。'));D.party.forEach(p=>{const button=btn(p.role+' · '+p.name,()=>chooseUnit(p.id),'wide');button.dataset.unitId=p.id;button.disabled=t.used.includes(p.id);b.append(button);});return;}
    const p=D.party.find(p=>p.id===selection.unitId);b.append(el('h3',p.role+' · '+p.name),el('p',p.description,'muted'));
    const label=el('label','目的地（也可直接點地圖）','label');label.htmlFor='destination-select';const select=el('select',undefined,'tile-selector');select.id='destination-select';select.append(el('option','請選擇三步內位置'));select.firstChild.value='';
    E.reachable(state,chapter,p.id).sort((a,b)=>a.distance-b.distance||a.y-b.y||a.x-b.x).forEach(tile=>{const option=el('option',`第 ${tile.x+1} 欄，第 ${tile.y+1} 列 · ${tile.distance} 步`);option.value=tile.x+','+tile.y;if(selection.destination?.x===tile.x&&selection.destination?.y===tile.y)option.selected=true;select.append(option);});select.addEventListener('change',()=>{selection.destination=select.value?{x:Number(select.value.split(',')[0]),y:Number(select.value.split(',')[1])}:null;render();focusTactics();});b.append(label,select);
    const skills=el('div',undefined,'skill-buttons');chapter.scenario.actions.filter(a=>a.unitId===p.id).forEach(action=>{const target=chapter.scenario.targets.find(t=>t.id===action.targetId);const button=btn('',()=>chooseAction(action),'skill-button'+(selection.actionId===action.id?' selected':''));button.dataset.actionId=action.id;button.append(el('strong',(t.flags.includes(action.flag)?'✓ ':'')+action.label),el('small',`${target.name} · ${costText(action.cost)}`));button.setAttribute('aria-pressed',selection.actionId===action.id?'true':'false');skills.append(button);});b.append(skills);
    const preview=selection.actionId&&selection.destination?E.preview(state,chapter,command()):null;const action=chapter.scenario.actions.find(a=>a.id===selection.actionId);
    b.append(el('div',preview?(preview.ok?`${action.preview}\n${costText(preview.cost)} · 移動 ${preview.distance} 步`:preview.message):'選擇技能後會預覽成本與作用。','cost-preview'+(preview&&!preview.ok?' invalid':'')));
    const confirm=btn('確認派遣 →',submitCommand,'gold-button wide');confirm.id='confirm-command';confirm.disabled=!preview?.ok||submitting;b.append(confirm,btn('等待／保留資源',()=>{if(submitting||state.phase!=='tactics'||!selection.unitId)return;submitting=true;finishCommand(E.wait(state,chapter,{token:state.revision,unitId:selection.unitId}));},'wide'),el('p','等待不消耗資源，會使用一次指令；可繼續推進到任務後果。','muted'),btn('重新選隊員',()=>{selection={unitId:null,actionId:null,destination:null};render();},'text-button wide'));
  }
  function finishCommand(result){selection={unitId:null,actionId:null,destination:null};submitting=false;if(transition(result)){if(state.phase==='tactics')focusTactics();if(result.event?.type==='update'&&state.phase==='tactics')show('情勢更新',[el('p',result.event.text),btn('依新資訊繼續部署',close,'gold-button wide')],'NEW INFORMATION');if(state.phase==='outcome'){document.querySelector('#task-body .gold-button')?.focus({preventScroll:true});toast('三回合結束，請查看任務後果。');}}}
  function submitCommand(){if(submitting||state.phase!=='tactics'||!selection.actionId||!selection.destination)return;submitting=true;finishCommand(E.execute(state,chapter,command()));}
  function renderOutcome(b){const result=E.outcome(state,chapter),path=chapter.scenario.paths.find(p=>p.id===state.pathId);b.append(el('div',result.title,'result-heading'),el('p',result.text),el('p','方案：'+path.label+'。'+path.tradeoff,'muted'));const actions=state.tactical.log.filter(item=>item.type==='action'&&item.actionId!=='wait').map(item=>chapter.scenario.actions.find(a=>a.id===item.actionId)?.label).filter(Boolean);b.append(el('p',actions.length?'本次已執行：'+actions.join('、'):'本次尚未執行技能，六次指令均為等待。','muted'));if(result.missing?.length)b.append(el('p','尚待補上的行動：'+result.missing.map(f=>chapter.scenario.actions.find(a=>a.flag===f)?.label||f).join('、'),'warning-text'));
    if(state.phase==='outcome'){b.append(btn('帶著結果進入回顧 →',()=>transition(E.interact(state,chapter,'review')),'gold-button wide'),btn('重試三回合策略',()=>retry(),'wide'));}
    if(state.phase==='review'){const f=el('form');f.id='reflection-form';[['reason','理由與教材依據','我為什麼這樣做？運用了哪個教材概念？'],['revision','何時會修正','誰承擔代價？出現什麼新資訊時，我會改變方案？']].forEach(([key,title,placeholder])=>{const l=el('label',title,'label');l.htmlFor='reflection-'+key;const ta=el('textarea');ta.id=l.htmlFor;ta.name=key;ta.required=true;ta.maxLength=6000;ta.placeholder=placeholder;ta.value=state.reflection[key];ta.addEventListener('input',()=>{const reason=f.elements.reason.value,revision=f.elements.revision.value;const result=E.setReflection(state,chapter,{reason,revision});if(result.ok){try{state=store.updateState(result.state);}catch(error){toast(error.message);}}else{toast(result.message);}});f.append(l,ta);});const submit=el('button','保存回顧，完成本章','gold-button wide');submit.type='submit';f.append(submit);f.addEventListener('submit',event=>{event.preventDefault();const updated=E.setReflection(state,chapter,{reason:f.elements.reason.value,revision:f.elements.revision.value});if(!updated.ok){toast(updated.message);return;}if(transition(E.complete(updated.state,chapter))){toast('本章已完成，獲得「'+chapter.reward.title+'」。');}});b.append(f,btn('重試策略（保留這次行動紀錄）',()=>retry(),'text-button wide'));}
    if(state.phase==='complete'){b.append(el('span',chapter.reward.title,'badge'),el('p',chapter.reward.story),el('p','紀念物：'+chapter.reward.item,'muted'),el('p','我的理由：'+state.reflection.reason),el('p','修正條件：'+state.reflection.revision));const next=D.chapters.find(c=>c.number===chapter.number+1);b.append(btn(next?'繼續下一章 →':'回到章節選單',()=>next?selectChapter(next.id):chapterMenu(),'gold-button wide'),btn('重新挑戰本章',()=>ask('重新挑戰本章','重新挑戰會另存這次紀錄，完成徽章仍保留。確定重新開始本章？',()=>selectChapter(chapter.id,true)),'wide'));}
  }
  function retry(){ask('重試策略','重試會保存這次策略紀錄並重設本章資源，已找到的線索保留；回顧草稿會清空。',()=>{selection={unitId:null,actionId:null,destination:null};transition(E.retry(state,chapter));});}
  function renderJournal(){const entries=[];state.clues.forEach(id=>entries.push({text:'取得線索：'+chapter.clues.find(c=>c.id===id).name}));if(state.sideDone)entries.push({text:'完成支線：'+chapter.sideQuest.name});(state.tactical?.log||[]).forEach(item=>entries.push({text:`回合 ${item.round} · ${item.text}`,event:item.type==='event'}));if(state.tacticalAttempts?.length)entries.unshift({text:`保留 ${state.tacticalAttempts.length} 次策略重試紀錄，可在紀錄中檢視。`});$('journal-count').textContent=String(entries.length);$('journal').replaceChildren(...entries.map(e=>el('li',e.text,e.event?'event':'')));}
  function nearby(){if(state.phase!=='exploration')return null;const near=t=>Math.abs(t.x-state.player.x)+Math.abs(t.y-state.player.y)<=1;const uncollected=chapter.clues.find(c=>!state.clues.includes(c.id)&&near(c));if(uncollected)return uncollected; if(!state.sideDone&&near(chapter.sideQuest))return {...chapter.sideQuest,id:'side'};if(near(chapter.map.gate))return {...chapter.map.gate,id:'gate',name:'任務站'};return bonus?.markers().find(near)||chapter.clues.find(near)||null;}
  function updateNearby(){const target=nearby();$('nearby-label').textContent=target?target.name:state.phase==='exploration'?'靠近 ! 標記，再按互動':phases[state.phase];$('interact-button').disabled=state.phase!=='exploration'||!target;document.querySelectorAll('[data-move]').forEach(b=>b.disabled=state.phase!=='exploration');}
  function interact(){if(!store.save)return onboarding();const target=nearby();if(!target)return toast('先靠近線索或任務站。');if(target.bonus)return bonus.openMarker(target.id);if(state.clues.includes(target.id)){show(target.name,[el('p',target.text),btn('繼續探索',close,'gold-button wide')]);return;}const result=E.interact(state,chapter,target.id);if(transition(result)&&target.id!=='gate'){const portrait=el('canvas',undefined,'dialogue-portrait');portrait.width=150;portrait.height=165;window.RPGWorld.portrait(portrait,null,null,null,target.id==='side'?'logistics':target.type==='person'?'liaison':'doctor');show(target.name,[portrait,el('p',target.text),...(target.id==='side'?[el('p',target.reward,'badge')]:[]),btn('收進日誌，繼續探索',close,'gold-button wide')],'DISCOVERY');}}
  function step(dx,dy){if(modal.open||state.phase!=='exploration'||!store.save)return;transition(E.move(state,chapter,dx,dy),{quiet:true,light:true});}
  function stopWalking(){clearInterval(walkTimer);clearInterval(routeTimer);walkTimer=null;routeTimer=null;walking=false;}
  function route(target){const map=chapter.map,blocked=(x,y)=>x<0||y<0||x>=map.width||y>=map.height||map.walls.some(w=>x>=w.x&&x<w.x+w.w&&y>=w.y&&y<w.y+w.h),start={x:state.player.x,y:state.player.y};const q=[{...start,path:[]}],seen=new Set([start.x+','+start.y]);for(let i=0;i<q.length;i++){const p=q[i];if(Math.abs(p.x-target.x)+Math.abs(p.y-target.y)<=1)return p.path;for(const [dx,dy]of[[0,-1],[-1,0],[1,0],[0,1]]){const x=p.x+dx,y=p.y+dy,k=x+','+y;if(!blocked(x,y)&&!seen.has(k)){seen.add(k);q.push({x,y,path:[...p.path,[dx,dy]]});}}}return null;}
  function routeTo(target){if(state.phase!=='exploration')return;stopWalking();const path=route(target);if(path===null)return toast('找不到可行路線。');if(!path.length){toast('已在旁邊，請按互動。');return;}toast('沿路前往 '+(target.name||'任務站')+'，到達後請按互動。');walking=true;let i=0;routeTimer=setInterval(()=>{if(modal.open||state.phase!=='exploration'){stopWalking();return;}if(i>=path.length){stopWalking();toast('已到達，請按互動。');render();return;}const [dx,dy]=path[i++];step(dx,dy);},world.reducedMotion?90:130);}
  function hint(){if(state.phase==='exploration'){const target=chapter.clues.find(c=>!state.clues.includes(c.id))||{...chapter.map.gate,name:'任務站'};routeTo(target);}else if(state.phase==='tactics')show('部署提示',[el('p','每回合兩次指令，同一隊員不能重複。方案需要的行動列在任務卡上，但仍可選其他行動承擔不同結果。'),el('p','選技能可帶入最近可用位置；在地圖或目的地選單改位置後，確認預覽仍顯示可執行。')]);else toast('請依任務指示繼續；手機可在地圖下方查看。');}
  function chapterMenu(){const list=el('nav',undefined,'chapter-modal-list');list.setAttribute('aria-label','自由選擇章節');D.chapters.forEach(c=>list.append(chapterButton(c)));show('選擇本週的冒險',[el('p','每章都有完整起始隊伍與資源。主線進度不會限制自由選章。','muted'),list],'THIRTEEN CHAPTERS');}
  function concepts(){const nodes=[el('p',chapter.topic,'muted')];chapter.concepts.forEach(c=>{const n=el('section',undefined,'concept');n.append(el('strong',c.term),el('p',c.text));nodes.push(n);});if(['u07','u10'].includes(chapter.id)){const links=el('div',undefined,'source-links');links.append(el('p','制度資料請注意日期與效力；政策規劃不等於法律已生效。'));D.sources.filter(s=>chapter.id==='u07'?s.id==='aac':s.id!=='aac').forEach(s=>{if(!s.url?.startsWith('https://'))return;const a=el('a',s.title+(s.checked?' · 查核 '+s.checked:''));a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';links.append(a);});nodes.push(links);}show('本章概念 · '+chapter.title,nodes,'CONCEPT CARDS');}
  function onboarding(){const art=el('div','探索地圖　／　指揮夥伴　／　留下理由','onboarding-art'),form=el('form'),label=el('label','你的暱稱','label'),input=el('input');input.type='text';input.id='nickname';input.name='nickname';input.maxLength=40;input.required=true;input.placeholder='例如：新進學員';input.autocomplete='off';label.htmlFor=input.id;const submit=el('button','加入小隊，開始本週任務 →','gold-button wide');submit.type='submit';form.append(label,input,el('p','不需要真實姓名或學號。紀錄保存在這個瀏覽器，換裝置前請匯出 JSON。','muted'),submit);form.addEventListener('submit',event=>{event.preventDefault();try{store.newProfile(input.value);state=store.getCurrent();const requested=new URLSearchParams(location.search).get('chapter');const entry=D.chapters.find(c=>c.id===requested)||D.chapters.find(c=>c.id==='u03')||D.chapters[0];state=store.startChapter(entry.id);chapter=entry;modal.close();render();toast('歡迎加入小隊，先閱讀本章任務簡報。');}catch(error){toast(error.message);}});show('小隊集合，準備出發',[art,partyRow(),el('p','你將和軍醫、聯絡員與後勤士官一起處理服務與救援任務。事情常有不只一種做法，你的理由會跟著行動留下。'),form],'WELCOME, CADET');}
  function download(filename,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('已送出下載；若沒有檔案，可用「查看備份文字」。');}
  function exportFile(kind){try{const date=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});download('國醫倫理冒險-'+date+'.'+kind,kind==='json'?store.exportJSON():store.exportCSV(),kind==='json'?'application/json;charset=utf-8':'text/csv;charset=utf-8');}catch(error){toast(error.message);}}
  function backupText(){try{const json=el('textarea',undefined,'backup-text');json.readOnly=true;json.setAttribute('aria-label','完整 JSON 備份文字');json.value=store.exportJSON();const csv=el('textarea',undefined,'backup-text');csv.readOnly=true;csv.setAttribute('aria-label','CSV 摘要文字');csv.value=store.exportCSV();show('備份文字',[el('p','下載若被攔截，可選取下方完整文字，另存 .json 或 .csv。JSON 才能完整復原。'),el('h3','JSON 完整備份'),json,btn('選取 JSON',()=>{json.focus();json.select();},'wide'),el('h3','CSV 學習摘要'),csv]);}catch(error){toast(error.message);}}
  function restoreJSON(raw){stopWalking();store.importJSON(raw);state=store.getCurrent();selection={unitId:null,actionId:null,destination:null};if(modal.open)modal.close();render();toast('新版備份已復原；若顯示存檔失敗，請立即匯出。');}
  function pasteBackup(){const label=el('label','完整 JSON 備份','label'),input=el('textarea',undefined,'backup-text');input.id='restore-json';input.spellcheck=false;label.htmlFor=input.id;show('貼上備份還原',[el('p','先備份目前紀錄，再貼上完整 JSON。格式或紀錄不符合規則時，會保留目前紀錄。'),label,input,btn('驗證並還原',()=>{const raw=input.value;ask('還原備份','確認以這份 JSON 取代目前新版紀錄？',()=>{try{restoreJSON(raw);}catch(error){toast(error.message);}});},'gold-button wide')],'RESTORE BACKUP');}
  function recordDetail(c){const r=store.save.records[c.id];if(!r)return;const entries=[...r.attempts,r.current];const nodes=entries.map((s,i)=>{const n=el('section',undefined,'concept');n.append(el('strong',`挑戰 ${i+1} · ${phases[s.phase]}`));if(s.tactical){const o=E.outcome(s,c);n.append(el('p',o.title+'：'+o.text));const ol=el('ol',undefined,'journal');[...(s.tacticalAttempts||[]),s.tactical].forEach((t,k)=>{t.log.forEach(l=>ol.append(el('li',`策略 ${k+1} / 回合 ${l.round}：${l.text}`)));});n.append(ol);}if(s.reflection.reason)n.append(el('p','理由與依據：'+s.reflection.reason));if(s.reflection.revision)n.append(el('p','修正條件：'+s.reflection.revision));return n;});show(c.title+' · 歷次紀錄',nodes,'LEARNING RECORD');}
  function records(){if(!store.save)return onboarding();const table=el('table',undefined,'records-table'),head=el('thead'),hr=el('tr');['章節','狀態','歷次','查看'].forEach(t=>hr.append(el('th',t)));head.append(hr);table.append(head);const tb=el('tbody');D.chapters.forEach(c=>{const r=store.save.records[c.id],tr=el('tr');tr.append(el('td',String(c.number).padStart(2,'0')+' '+c.title),el('td',done(c.id)?'曾完成':r?phases[r.current.phase]:'未開始'),el('td',r?String(r.attempts.length+1):'—'));const td=el('td');if(r)td.append(btn('查看',()=>recordDetail(c)));tr.append(td);tb.append(tr);});table.append(tb);const wrap=el('div',undefined,'table-scroll');wrap.append(table);const actions=el('div',undefined,'record-actions');actions.append(btn('備份 JSON',()=>exportFile('json')),btn('學習摘要 CSV',()=>exportFile('csv')),btn('匯入 JSON',()=>ask('選取備份檔案','匯入會取代新版目前紀錄。請先備份；舊版或不合規檔案會拒絕。確定選取備份？',()=>$('import-file').click())),btn('查看備份文字',backupText),btn('貼上備份還原',pasteBackup),btn('建立新學員紀錄',()=>ask('建立新學員紀錄','建立新紀錄會取代目前新版紀錄；請先匯出 JSON。舊版紀錄不受影響。確定建立？',onboarding)));const rewards=el('ul',undefined,'reward-list');D.chapters.filter(c=>done(c.id)).forEach(c=>{const n=el('li');n.append(el('strong',c.reward.title+' · '+c.reward.item),el('span',c.reward.story));rewards.append(n);});show('冒險紀錄 · '+store.save.nickname,[el('p',`${store.completedCount()} / 13 章曾完成。重試不會移除已取得稱號；正式評量由老師判讀。`),wrap,actions,el('h3','稱號、紀念物與夥伴故事'),rewards.children.length?rewards:el('p','完成第一章後，第一件紀念物會出現在這裡。','muted')],'FIELD ARCHIVE');}
  function helpNodes(){const table=el('table',undefined,'help-table');[['移動','方向鍵 / WASD，或地圖下方方向按鈕'],['互動','靠近標記後按 E 或互動按鈕'],['找路','H、目前目標與路線，或線索旁的路線按鈕'],['策略','點隊員 → 選位置 → 選技能 → 確認派遣'],['回顧','兩欄短句，說明教材依據與修正條件'],['備份','紀錄 → 備份 JSON；換瀏覽器前先備份']].forEach(([a,b])=>{const tr=el('tr');tr.append(el('td',a),el('td',b));table.append(tr);});return [table,el('p','每回合兩次指令、不同隊員各一次。三回合後無論策略成功或有缺口，都能回顧；需要時可重試。','muted'),el('p','使用老師提供的遊戲網址，可在電腦與手機瀏覽器遊玩。進度只保存在目前瀏覽器。','muted')];}
  function settings(){
    const label=el('label',undefined,'check-row'),check=el('input');check.type='checkbox';check.checked=!!store.save?.settings.reducedMotion;label.append(check,el('span','減少角色晃動與操作動畫'));check.addEventListener('change',()=>{if(!store.save)return;try{store.setSettings({reducedMotion:check.checked});render();}catch(error){toast(error.message);check.checked=!!store.save?.settings.reducedMotion;}});
    const section=el('section',undefined,'music-setting'),enabled=el('input'),enabledLabel=el('label',undefined,'check-row');enabled.id='settings-music-enabled';enabled.type='checkbox';enabled.checked=music.getStatus().enabled;enabledLabel.append(enabled,el('span','播放原創背景音樂'));
    enabled.addEventListener('change',()=>{if(musicSettings({musicEnabled:enabled.checked})&&enabled.checked)music.unlock();});
    const volumeLabel=el('label','音量','label'),value=el('output',Math.round(music.getStatus().volume*100)+'%'),range=el('input');value.id='settings-music-value';value.htmlFor='settings-music-volume';volumeLabel.htmlFor='settings-music-volume';volumeLabel.append(value);range.id='settings-music-volume';range.type='range';range.min='0';range.max='100';range.step='5';range.value=String(Math.round(music.getStatus().volume*100));range.addEventListener('input',()=>musicSettings({musicVolume:Number(range.value)/100}));
    section.append(enabledLabel,volumeLabel,range,el('p','第一次操作後開始播放。音樂與提示音共用音量與開關；背景頁籤會暫停，返回後續播。設定會跟著紀錄保存。','muted'));
    show('設定與操作說明',[section,label,...helpNodes(),el('p','清除瀏覽資料或改用不同網址可能看不到紀錄；資料夾中的程式備份不等於學生存檔。','warning-text')]);
  }
  $('music-button').addEventListener('click',()=>{const status=music.getStatus();if(status.enabled&&status.playing)musicSettings({musicEnabled:false});else if(musicSettings({musicEnabled:true}))music.unlock();});
  $('music-volume').addEventListener('input',event=>musicSettings({musicVolume:Number(event.target.value)/100}));
  // 音源只從真正的使用者操作啟動；讀檔與畫面重繪不建立音源。
  const unlockMusic=event=>{if(event.isTrusted&&!event.target.closest('#music-button')&&!event.ctrlKey&&!event.metaKey&&!event.altKey)music.unlock();};
  document.addEventListener('pointerdown',unlockMusic,{capture:true});document.addEventListener('keydown',unlockMusic,{capture:true});
  $('modal-close').addEventListener('click',close);modal.addEventListener('cancel',stopWalking);$('chapters-button').addEventListener('click',chapterMenu);$('concepts-button').addEventListener('click',concepts);$('records-button').addEventListener('click',records);$('settings-button').addEventListener('click',settings);$('help-button').addEventListener('click',()=>show('操作說明',helpNodes()));$('interact-button').addEventListener('click',interact);$('hint-button').addEventListener('click',hint);
  $('bonus-button').addEventListener('click',()=>bonus?bonus.open():toast('支線內容尚未載入。'));
  document.querySelectorAll('.header-actions button').forEach(button=>button.addEventListener('click',()=>music.effect('menu')));
  $('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw new Error('JSON 超過 2 MB，未修改目前紀錄。');restoreJSON(await file.text());}catch(error){toast(error.message);}finally{event.target.value='';}});
  const dirs={up:[0,-1],left:[-1,0],right:[1,0],down:[0,1]};document.querySelectorAll('[data-move]').forEach(button=>{button.addEventListener('pointerdown',event=>{event.preventDefault();stopWalking();if(button.disabled)return;button.setPointerCapture(event.pointerId);const [dx,dy]=dirs[button.dataset.move];step(dx,dy);walkTimer=setInterval(()=>step(dx,dy),140);});['pointerup','pointercancel','lostpointercapture'].forEach(type=>button.addEventListener(type,stopWalking));button.addEventListener('click',event=>{if(event.detail===0){stopWalking();step(...dirs[button.dataset.move]);}});});
  document.addEventListener('keydown',event=>{if(modal.open||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;const keys={ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1],ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0]};if(keys[event.key]&&state.phase==='exploration'){event.preventDefault();stopWalking();step(...keys[event.key]);}else if(event.key.toLowerCase()==='e'){event.preventDefault();interact();}else if(event.key.toLowerCase()==='h'){event.preventDefault();hint();}});
  $('scene').addEventListener('pointerdown',event=>{if(modal.open)return;stopWalking();const tile=world.tileAt(event.clientX,event.clientY);if(state.phase==='tactics'){if(tile.x<0||tile.x>5||tile.y<0||tile.y>7)return;const unit=state.tactical.units.find(u=>u.x===tile.x&&u.y===tile.y);if(unit&&!state.tactical.used.includes(unit.id)){chooseUnit(unit.id);return;}if(selection.unitId&&E.reachable(state,chapter,selection.unitId).some(t=>t.x===tile.x&&t.y===tile.y)){selection.destination=tile;render();}else toast('先選隊員，再點可到達的綠色格子。');}else if(state.phase==='exploration'){const target=chapter.clues.find(c=>c.x===tile.x&&c.y===tile.y)||(chapter.sideQuest.x===tile.x&&chapter.sideQuest.y===tile.y?chapter.sideQuest:null)||bonus?.markers().find(m=>m.x===tile.x&&m.y===tile.y)||(chapter.map.gate.x===tile.x&&chapter.map.gate.y===tile.y?{...chapter.map.gate,name:'任務站'}:null);if(target)routeTo(target);}});
  document.addEventListener('visibilitychange',()=>{stopWalking();if(document.hidden){world.stop();music.pause();}else{world.start();music.resume();}});window.addEventListener('blur',stopWalking);
  window.addEventListener('pagehide',()=>music.pause());window.addEventListener('pageshow',()=>{if(document.hidden)music.pause();else music.resume();});
  try{store.load();state=store.save?store.getCurrent():E.createState(D.chapters[0]);chapter=D.chapters.find(c=>c.id===state.chapterId);render();if(!store.save)onboarding();}catch(error){show('遊戲無法載入',[el('p',error.message),el('p','請保留紀錄，重新啟動遊戲；不要先清除瀏覽資料。')]);}
})();



