'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),Avatar=require('../js/engine/rpg_avatar'),UI=require('../js/rpg_avatar_ui');
class Node{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.events={};this.dataset={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,fn){this.events[k]=fn;}getContext(){return new Proxy({},{get:()=>()=>{},set:()=>true});}trigger(type){this.events[type]?.({target:this});}all(){return[this,...this.children.flatMap(n=>n.all?n.all():[])];}}
const document={createElement:tag=>new Node(tag)};
test('editor uses labeled native selects and buttons with an accessible preview description',()=>{const ui=new UI({document});for(const[key,select]of Object.entries(ui.controls)){assert.equal(select.tagName,'SELECT');assert.equal(select.id,'avatar-'+key);assert.equal(select.children.length,Avatar.catalog[key].length);assert.ok(ui.element.all().find(n=>n.tagName==='LABEL'&&n.htmlFor===select.id));}assert.equal(ui.canvas.attributes.role,'img');assert.match(ui.canvas.attributes['aria-label'],/角色預覽/);assert.equal(ui.summary.attributes['aria-live'],'polite');assert.equal(ui.presetButtons.length,4);for(const[,button]of ui.presetButtons)assert.equal(button.type,'button');});
test('preset choice and individual clothing controls update the visible preview and selected state',()=>{const ui=new UI({document});ui.presetButtons[1][1].trigger('click');assert.equal(ui.getValue().hair,'pony');assert.equal(ui.controls.top.value,'jacket');assert.equal(ui.presetButtons[1][1].attributes['aria-pressed'],'true');ui.controls.topColor.value='navy';ui.controls.topColor.trigger('change');assert.equal(ui.getValue().topColor,'navy');assert.match(ui.canvas.attributes['aria-label'],/深藍/);assert.ok(ui.presetButtons.every(([,b])=>b.attributes['aria-pressed']==='false'));});
test('editing and reset stay in a draft until the caller confirms',()=>{const original={...Avatar.presets[1].value};const ui=new UI({document,value:original});ui.controls.hair.value='long';ui.controls.hair.trigger('change');assert.equal(original.hair,'pony');const reset=ui.element.all().find(n=>n.textContent==='重設外觀');reset.trigger('click');assert.deepEqual(ui.getValue(),Avatar.defaults);assert.equal(original.hair,'pony');const returned=ui.getValue();returned.skin='ebony';assert.equal(ui.getValue().skin,'peach');});
test('all touch controls have 44px sizing; narrow layouts stack and respect reduced motion',()=>{const css=fs.readFileSync('css/avatar.css','utf8');assert.match(css,/min-height:44px/);assert.match(css,/@media\(max-width:680px\)/);assert.match(css,/grid-template-columns:1fr/);assert.match(css,/font-size:16px/);assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion/);});
test('main entry loads avatar module before renderer and offers an always reachable editor',()=>{const html=fs.readFileSync('legacy-v1/index.html','utf8'),app=fs.readFileSync('js/rpg_app.js','utf8');assert.ok(html.indexOf('js/engine/rpg_avatar.js')<html.indexOf('js/engine/rpg_world.js'));assert.match(html,/id="avatar-button"/);assert.match(app,/new window.RPGAvatarUI/);assert.match(app,/btn\('取消',close\)/);assert.match(app,/saveAvatar\(studio.getValue\(\)\)/);assert.match(app,/music.setChapter\(chapter.id\)/);});
test('preview build isolates cosmetic preferences from production',()=>{const build=fs.readFileSync('scripts/build-preview.js','utf8');assert.match(build,/replaceAll\('ndmu-ethics-rpg:avatar:v1',savePrefix\+':avatar:v1'\)/);assert.match(build,/ndmu-ethics-rpg-avatar-preview/);assert.match(build,/ndmu-ethics-classroom-avatar-preview-outbox:v1/);});

test('queued modal close never unducks a reopened editor',()=>{const app=fs.readFileSync('js/rpg_app.js','utf8');assert.match(app,/modal\.addEventListener\('close',\(\)=>music\.setScene\(modal\.open\?'dialogue':state\.phase\)\)/);});

test('isolated public avatar preview disables collection and never uses production or older preview storage keys',()=>{const html=fs.readFileSync('preview/avatar-audio/index.html','utf8');assert.match(html,/window.ClassroomConfig=\{enabled:false,collectorUrl:'',sessionId:'',assignedChapter:''/);for(const key of['ndmu-ethics-rpg:v1','ndmu-ethics-rpg:bonus:v1','ndmu-ethics-rpg:avatar:v1','ndmu-ethics-classroom-outbox:v1','ndmu-ethics-rpg-preview:v1','ndmu-ethics-rpg-preview:bonus:v1'])assert.ok(!html.includes("'"+key+"'"),key);for(const key of['ndmu-ethics-rpg-avatar-preview:v1','ndmu-ethics-rpg-avatar-preview:bonus:v1','ndmu-ethics-rpg-avatar-preview:avatar:v1','ndmu-ethics-classroom-avatar-preview-outbox:v1'])assert.ok(html.includes("'"+key+"'"),key);assert.ok(!/AKfy[a-zA-Z0-9_-]{20,}|AIza[0-9A-Za-z_-]{20,}|ghp_[a-zA-Z0-9]{20,}|BEGIN .*PRIVATE KEY/.test(html));assert.ok(!/<script[^>]+src="https?:/.test(html));assert.match(html,/角色與配樂預覽 · 收件已關閉/);});

test('preset hover overrides the old global dark button hover without losing label contrast',()=>{const css=fs.readFileSync('css/avatar.css','utf8'),global=fs.readFileSync('css/rpg.css','utf8');assert.match(global,/button:not\(:disabled\):hover\{background:#476348\}/);assert.match(css,/\.avatar-preset:not\(:disabled\):hover\{background:#e5edda;color:#294b42;\}/);assert.match(css,/\.avatar-preset\[aria-pressed="true"\]:not\(:disabled\):hover\{background:#d9e8d5;color:#294b42;\}/);});
