'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const World=require('../js/engine/rpg_world'),Data=require('../js/data/rpg_chapters'),Engine=require('../js/engine/rpg_engine');
function canvas(width=960,height=640){const fn=()=>{};const context=new Proxy({createLinearGradient:()=>({addColorStop:fn})},{get:(o,k)=>k in o?o[k]:fn,set:(o,k,v)=>{o[k]=v;return true}});return{width,height,getContext:()=>context,getBoundingClientRect:()=>({left:20,top:30,width,height})};}
test('wide renderer keeps the trusted chapter map and save state unchanged',()=>{const c=Data.chapters[2],s=Engine.createState(c),before=JSON.stringify(s),map=JSON.stringify(c.map);const world=new World(canvas(),{party:Data.party});world.set(s,c);assert.equal(JSON.stringify(s),before);assert.equal(JSON.stringify(c.map),map);assert.equal(world.W,960);assert.equal(world.H,640)});
test('exploration pointer mapping accounts for camera, scale and page offsets',()=>{const world=new World(canvas());world.state={phase:'exploration'};world.camera={x:120,y:240};assert.deepEqual(world.tileAt(20+24,30+24),{x:3,y:5});});
test('mobile uses tall camera without changing map coordinates',()=>{const world=new World(canvas(390,488));assert.equal(world.W,640);assert.equal(world.H,800);world.state={phase:'exploration'};world.camera={x:48,y:96};assert.deepEqual(world.tileAt(20+390*.075,30+488*.06),{x:2,y:3});});
test('tactical target mapping matches the rendered wide board',()=>{const world=new World(canvas());world.state={phase:'tactics'};const b=world.board();assert.deepEqual(world.tileAt(20+b.x+b.t*2.5,30+b.y+b.t*5.5),{x:2,y:5});});
test('tactical target mapping stays aligned on mobile',()=>{const world=new World(canvas(390,488));world.state={phase:'tactics'};const b=world.board();const x=(b.x+b.t*3.5)*390/640,y=(b.y+b.t*4.5)*488/800;assert.deepEqual(world.tileAt(20+x,30+y),{x:3,y:4});});
test('camera clamps to the authored perimeter at map boundaries',()=>{const c=Data.chapters[2],world=new World(canvas());world.set(Engine.createState(c),c);world.state={...world.state,player:{x:0,y:0,facing:'up'}};world.setCamera(true);assert.equal(world.camera.x,-180);assert.equal(world.camera.y,-130);world.state.player={x:15,y:19,facing:'down'};world.setCamera(true);assert.ok(world.camera.x<=768-world.W*.55);assert.ok(world.camera.y<=960-world.H+190);});
test('portraits show original fallback without a browser Image API',()=>{assert.doesNotThrow(()=>World.portrait(canvas(90,100),null,null,null,'doctor'));});
test('generated portrait loads are cached and stale callbacks cannot overwrite a newer identity',()=>{const oldImage=global.Image,oldAssets=global.RPG_PORTRAIT_ASSETS;const images=[],drawn=[];global.RPG_PORTRAIT_ASSETS={cadet:'test-cadet.webp',doctor:'test-doctor.webp'};global.Image=class{constructor(){images.push(this);this.naturalWidth=512;this.naturalHeight=512;}};try{const c=canvas(90,100);c.getContext('2d').drawImage=(image)=>drawn.push(image.src);World.portrait(c,null,null,null,'cadet');World.portrait(c,null,null,null,'doctor');images[0].onload();assert.deepEqual(drawn,[]);images[1].onload();assert.deepEqual(drawn,['test-doctor.webp']);World.portrait(c,null,null,null,'doctor');assert.equal(images.length,2);assert.equal(drawn.length,2);}finally{global.Image=oldImage;global.RPG_PORTRAIT_ASSETS=oldAssets;}});
test('failed generated portrait preserves the original fallback and does not throw',()=>{const oldImage=global.Image,oldAssets=global.RPG_PORTRAIT_ASSETS;let image;global.RPG_PORTRAIT_ASSETS={liaison:'test-failed.webp'};global.Image=class{constructor(){image=this;}};try{World.portrait(canvas(90,100),null,null,null,'liaison');assert.doesNotThrow(()=>image.onerror());assert.doesNotThrow(()=>World.portrait(canvas(90,100),null,null,null,'liaison'));}finally{global.Image=oldImage;global.RPG_PORTRAIT_ASSETS=oldAssets;}});
test('all thirteen distinct layouts render at both sizes without changing learning state',()=>{const Maps=require('../js/data/rpg_maps');for(const original of Data.chapters)for(const size of[[960,640],[390,488]]){const c=Maps.apply(original),world=new World(canvas(...size));let s=Engine.createState(c);const before=JSON.stringify(s),map=JSON.stringify(c.map);world.set(s,c);assert.equal(JSON.stringify(s),before,c.id);assert.equal(JSON.stringify(c.map),map,c.id);s=Engine.choosePath({...s,phase:'planning',clues:c.clues.map(a=>a.id),player:{x:8,y:4,facing:'up'}},c,c.scenario.paths[0].id).state;const tactical=JSON.stringify(s);world.set(s,c,{unitId:'cadet'},Engine.reachable(s,c,'cadet'));assert.equal(JSON.stringify(s),tactical,c.id);}});
test('changing chapter invalidates cached terrain while phase changes preserve it',()=>{const world=new World(canvas());let c=Data.chapters[0],s=Engine.createState(c);world.set(s,c);world.floor={cached:true};world.set({...s,phase:'exploration'},c);assert.deepEqual(world.floor,{cached:true});c=Data.chapters[1];world.set(Engine.createState(c),c);assert.equal(world.floor,null);});
test('cached generated portraits paint freshly created canvases before DOM attachment',()=>{const oldImage=global.Image,oldAssets=global.RPG_PORTRAIT_ASSETS;let image;global.RPG_PORTRAIT_ASSETS={logistics:'test-detached.webp'};global.Image=class{constructor(){image=this;this.naturalWidth=512;this.naturalHeight=512;}};try{const first=canvas(90,100);World.portrait(first,null,null,null,'logistics');image.onload();let draws=0;const next=canvas(90,100);next.isConnected=false;next.getContext('2d').drawImage=()=>draws++;World.portrait(next,null,null,null,'logistics');assert.equal(draws,1);}finally{global.Image=oldImage;global.RPG_PORTRAIT_ASSETS=oldAssets;}});

test('east-edge actors stay clear of the desktop mission overlay',()=>{const c=Data.chapters[2],world=new World(canvas());world.set(Engine.createState(c),c);world.state={...world.state,player:{x:15,y:18,facing:'right'}};world.setCamera(true);const actorScreenX=(15+.5)*World.TILE-world.camera.x;assert.ok(actorScreenX<world.W*.6,'Actor must stay left of the opaque mission panel');});
