'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Avatar=require('../js/engine/rpg_avatar'),World=require('../js/engine/rpg_world'),Data=require('../js/data/rpg_chapters'),Engine=require('../js/engine/rpg_engine'),Store=require('../js/engine/rpg_store');
function storage(){const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),map:m};}
function canvas(width=240,height=260){const calls=[],fn=()=>{};const ctx=new Proxy({calls,fillRect(...args){calls.push([this.fillStyle,...args]);},createLinearGradient:()=>({addColorStop:fn})},{get:(o,k)=>k in o?o[k]:fn,set:(o,k,v)=>{o[k]=v;return true}});return{width,height,getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width,height})};}
test('avatar normalization accepts only cosmetic catalog values, never identity or scoring fields',()=>{const v=Avatar.normalize({...Avatar.presets[1].value,name:'Student',studentId:'private',score:999,__proto__:{top:'unsafe'},skin:'<script>',gear:'unknown'});assert.equal(v.skin,Avatar.defaults.skin);assert.equal(v.gear,'none');assert.equal(v.hair,'pony');assert.equal(Object.hasOwn(v,'name'),false);assert.equal(Object.hasOwn(v,'score'),false);assert.deepEqual(Object.keys(v).sort(),['version',...Object.keys(Avatar.catalog)].sort());});
test('missing, malformed and future fields fall back without requiring progress migration',()=>{for(const input of[null,undefined,[],4,'invalid',{version:99,hair:'long',extra:{x:1}}]){const v=Avatar.normalize(input);assert.equal(v.version,1);for(const[k,list]of Object.entries(Avatar.catalog))assert.ok(list.some(c=>c.id===v[k]));}assert.equal(Avatar.normalize({version:99,hair:'long'}).hair,'long');});
test('all styles combine freely; no gender, locks, currency or rewards in the catalog',()=>{assert.equal(Object.hasOwn(Avatar.catalog,'gender'),false);assert.equal(Avatar.presets.length,4);for(const [key,list]of Object.entries(Avatar.catalog))for(const choice of list){const input={...Avatar.presets[1].value,[key]:choice.id};assert.deepEqual(Avatar.normalize(input),input);assert.ok(choice.name);}assert.ok(Avatar.catalog.skin.length>=6);assert.ok(Avatar.catalog.hair.length>=5);});
test('avatar persistence uses its own key and leaves preexisting learning progress byte-for-byte unchanged',()=>{const s=storage();s.setItem('ndmu-ethics-rpg:v1','existing-learning-save');const a=new Avatar.Store(s);assert.deepEqual(a.value,Avatar.defaults);assert.equal(a.save(Avatar.presets[3].value),true);assert.equal(s.getItem('ndmu-ethics-rpg:v1'),'existing-learning-save');assert.deepEqual(new Avatar.Store(s).value,Avatar.presets[3].value);assert.deepEqual([...s.map.keys()].sort(),[Avatar.KEY,'ndmu-ethics-rpg:v1'].sort());});
test('corrupted or blocked storage remains usable and reports unsaved cosmetic state',()=>{const s=storage();s.setItem(Avatar.KEY,'{bad');const a=new Avatar.Store(s);assert.deepEqual(a.value,Avatar.defaults);for(const bad of[null,{getItem(){throw Error('blocked');},setItem(){throw Error('full');}}]){const b=new Avatar.Store(bad);assert.equal(b.save(Avatar.presets[1].value),false);assert.equal(b.persisted,false);assert.equal(b.value.hair,'pony');}});
test('save/get returns normalized copies; caller mutations never modify catalog defaults',()=>{const s=storage(),a=new Avatar.Store(s),v={...Avatar.defaults};a.save(v);v.hair='long';assert.equal(a.value.hair,'crop');const loaded=a.load();loaded.hair='long';assert.equal(a.value.hair,'crop');assert.ok(Object.isFrozen(Avatar.catalog.skin));assert.ok(Object.isFrozen(Avatar.presets[0].value));});
test('each individual appearance option changes actual rendered pixels',()=>{function signature(value){const c=canvas();Avatar.portrait(c,value);return JSON.stringify(c.getContext().calls);}const base=signature(Avatar.defaults);for(const[key,list]of Object.entries(Avatar.catalog))for(const option of list){if(option.id===Avatar.defaults[key])continue;assert.notEqual(signature({...Avatar.defaults,[key]:option.id}),base,key+':'+option.id);}});
test('all presets render in every direction and walking phase without mutating values',()=>{for(const p of Avatar.presets)for(const direction of['up','down','left','right'])for(const walk of[0,1,3]){const before=JSON.stringify(p.value),ctx=canvas().getContext();assert.doesNotThrow(()=>Avatar.draw(ctx,100,140,p.value,3,direction,walk,true));assert.equal(JSON.stringify(p.value),before);assert.ok(ctx.calls.length>30);}});
test('changing the player appearance leaves all thirteen chapter states and tactical units unchanged',()=>{for(const ch of Data.chapters){const c=canvas(960,640),world=new World(c),s=Engine.createState(ch),before=JSON.stringify(s),data=JSON.stringify(ch);world.set(s,ch);world.setAvatar(Avatar.presets[1].value);assert.equal(JSON.stringify(s),before);assert.equal(JSON.stringify(ch),data);assert.equal(world.avatar.hair,'pony');}});
test('existing learning saves export the exact same bytes after cosmetic changes',()=>{const s=storage(),game=new Store({storage:s,chapters:Data.chapters});game.newProfile('QA');const before=game.exportJSON();new Avatar.Store(s).save(Avatar.presets[1].value);assert.equal(game.exportJSON(),before);});
