'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Music=require('../js/engine/rpg_audio');
function harness({recorded=false}={}){
 const sources=[],timers=new Map();let next=1;
 const param=()=>({value:0,cancelScheduledValues(){},setTargetAtTime(v){this.value=v},setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v},exponentialRampToValueAtTime(v){this.value=v}});
 const node=()=>({gain:param(),frequency:param(),Q:param(),connect(){},disconnect(){this.disconnected=true},start(time,offset){this.started={time,offset}},stop(time){this.stopped=time}});
 const context={currentTime:0,state:'running',destination:{},createGain:node,createBiquadFilter:node,createOscillator(){const n=node();sources.push(n);return n},createBufferSource(){const n=node();sources.push(n);return n},resume(){this.state='running';return Promise.resolve()},close(){this.state='closed';return Promise.resolve()}};
 if(recorded)context.decodeAudioData=async()=>({duration:49});
 const music=new Music({contextFactory:()=>context,timer:{setInterval(fn){const id=next++;timers.set(id,fn);return id},clearInterval(id){timers.delete(id)}}});
 return{music,context,sources,timers};
}
test('music does not create sources until an explicit unlock',()=>{const h=harness();h.music.setScene('tactics');h.music.setVolume(.4);assert.equal(h.sources.length,0);assert.equal(h.music.playing,false);h.music.destroy()});
test('disabled music stays silent across unlock and resume',async()=>{const h=harness();h.music.setEnabled(false);assert.equal(await h.music.unlock(),false);await h.music.resume();assert.equal(h.sources.length,0);h.music.destroy()});
test('volume clamps safely and rejects invalid values',()=>{const h=harness();h.music.setVolume(5);assert.equal(h.music.volume,1);h.music.setVolume(-1);assert.equal(h.music.volume,0);assert.equal(h.music.setVolume(NaN),false);h.music.destroy()});
test('pause stops scheduling and resume restarts only once',async()=>{const h=harness();await h.music.unlock();assert.equal(h.timers.size,1);h.music.pause();assert.equal(h.timers.size,0);assert.equal(h.music.playing,false);await h.music.resume();await h.music.unlock();assert.equal(h.timers.size,1);h.music.destroy();assert.equal(h.timers.size,0)});
test('effects never bypass mute, autoplay or paused state',async()=>{const h=harness();h.music.effect('discovery');assert.equal(h.sources.length,0);await h.music.unlock();h.music.setVolume(0);const n=h.sources.length;h.music.effect('complete');assert.equal(h.sources.length,n);h.music.setVolume(.2);h.music.pause();h.music.effect();assert.equal(h.sources.length,n);h.music.destroy()});
test('recorded track fetches only local asset and starts after decode',async()=>{const old=global.fetch,urls=[];global.fetch=async url=>{urls.push(url);return{ok:true,arrayBuffer:async()=>new ArrayBuffer(1)}};try{const h=harness({recorded:true});await h.music.unlock();await h.music.trackRequest;assert.deepEqual(urls,['assets/audio/menu.mp3','assets/audio/confirm.mp3','assets/audio/clue.mp3','assets/audio/morning-base.mp3']);assert.ok(h.music.trackSource);assert.equal(h.music.trackSource.loop,true);h.music.destroy()}finally{global.fetch=old}});
test('recorded playback resumes its position after background pause',async()=>{const old=global.fetch;global.fetch=async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});try{const h=harness({recorded:true});await h.music.unlock();await h.music.trackRequest;h.context.currentTime=12;h.music.pause();assert.equal(h.music.trackOffset,12);await h.music.resume();assert.equal(h.music.trackSource.started.offset,12);h.music.destroy()}finally{global.fetch=old}});
test('failed track fetch keeps the synthesis fallback playable',async()=>{const old=global.fetch;global.fetch=async()=>({ok:false});try{const h=harness({recorded:true});await h.music.unlock();await h.music.trackRequest;assert.equal(h.music.trackFailed,true);assert.equal(h.music.playing,true);assert.equal(h.music.trackSource,null);assert.ok(h.sources.length>0);h.music.destroy()}finally{global.fetch=old}});
test('late track decode does not restart playback while paused',async()=>{const old=global.fetch;let resolve;global.fetch=()=>new Promise(r=>{resolve=r});try{const h=harness({recorded:true});await h.music.unlock();h.music.pause();resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});await h.music.trackRequest;assert.equal(h.music.trackSource,null);assert.equal(h.music.playing,false);h.music.destroy()}finally{global.fetch=old}});
test('late track decode does not start after destroy',async()=>{const old=global.fetch;let resolve;global.fetch=()=>new Promise(r=>{resolve=r});try{const h=harness({recorded:true});await h.music.unlock();h.music.destroy();resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});await h.music.trackRequest;assert.equal(h.music.trackSource,null);assert.equal(h.music.playing,false)}finally{global.fetch=old}});
test('decoded original clue effect uses its audio buffer and respects mute',async()=>{const old=global.fetch;global.fetch=async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});try{const h=harness({recorded:true});await h.music.unlock();await Promise.all(h.music.effectRequests);await h.music.trackRequest;h.music.effect('discovery');assert.equal(h.sources.at(-1).buffer,h.music.effects.get('clue'));const count=h.sources.length;h.music.setEnabled(false);h.music.effect('confirm');assert.equal(h.sources.length,count);h.music.destroy()}finally{global.fetch=old}});
test('unavailable recorded effects fall back without blocking BGM',async()=>{const old=global.fetch;global.fetch=async url=>({ok:url.endsWith('morning-base.mp3'),arrayBuffer:async()=>new ArrayBuffer(1)});try{const h=harness({recorded:true});await h.music.unlock();await Promise.all(h.music.effectRequests);await h.music.trackRequest;assert.equal(h.music.effects.size,0);assert.ok(h.music.trackSource);const count=h.sources.length;h.music.effect('confirm');assert.equal(h.sources.length,count+2);h.music.destroy()}finally{global.fetch=old}});
test('late effect loads stay silent and are discarded after destruction',async()=>{const old=global.fetch,resolves=[];global.fetch=()=>new Promise(resolve=>resolves.push(resolve));try{const h=harness({recorded:true});await h.music.unlock();h.music.destroy();const count=h.sources.length;for(const resolve of resolves)resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});await Promise.all(h.music.effectRequests);await h.music.trackRequest;assert.equal(h.music.effects.size,0);assert.equal(h.sources.length,count)}finally{global.fetch=old}});
