'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const B=require('../js/engine/rpg_bonus'),C=require('../js/data/rpg_bonus_content'),Maps=require('../js/data/rpg_maps');
const chapters=require('../js/data/rpg_chapters').chapters.map(Maps.apply);
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.value='';}append(...nodes){this.children.push(...nodes);}setAttribute(k,v){this[k]=v;}addEventListener(k,f){this.listeners[k]=f;}focus(){}select(){}}
function fixture(){const context={RPGBonus:B,RPGBonusContent:C,document:{createElement:t=>new Element(t)}};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../js/rpg_bonus_ui.js'),'utf8'),context);const f={chapter:chapters[2],profile:{createdAt:'fictional-profile-a'},values:new Map(),writes:[],messages:[]};f.ui=new context.RPGBonusUI({storage:{getItem:k=>f.values.get(k),setItem:(k,v)=>{f.values.set(k,v);f.writes.push(k)}},getProfile:()=>f.profile,getChapter:()=>f.chapter,getChapters:()=>chapters,getState:()=>({phase:'exploration'}),show:(title,nodes,kicker)=>{f.dialog={title,nodes,kicker}},toast:m=>f.messages.push(m),close:()=>{},routeTo:()=>{},download:()=>{}});return f;}
test('optional UI renders every chapter, marker and puzzle kind through the public contract',()=>{const f=fixture();for(const c of chapters){f.chapter=c;f.ui.open();assert.ok(f.dialog.nodes.length);for(const m of C.getChapter(c.id).markers){f.ui.openMarker(m.id);assert.equal(f.dialog.title,m.name);}for(const p of C.getChapter(c.id).puzzles){f.ui.puzzle(p.id);assert.equal(f.dialog.title,p.title);assert.ok(f.dialog.nodes.some(n=>n.tagName==='FORM'));}}assert.ok(f.writes.every(k=>k.startsWith(B.STORAGE_KEY)));});
test('optional marker placement is unique and follows reachable map bonus slots',()=>{const f=fixture();for(const c of chapters){f.chapter=c;const markers=f.ui.markers(),slots=Object.values(c.map.bonusSpots).map(p=>p.x+','+p.y);assert.equal(new Set(markers.map(m=>m.x+','+m.y)).size,markers.length);assert.ok(markers.every(m=>slots.includes(m.x+','+m.y)));}});
test('personal record boards contain no fabricated class players',()=>{const f=fixture();f.ui.boards();assert.equal(f.dialog.title,'個人紀錄榜');assert.match(f.dialog.nodes[0].textContent,/尚未連接班級榜/);assert.match(f.dialog.nodes[0].textContent,/不替倫理立場/);});
test('new main profiles do not silently inherit another local profile bonus progress',()=>{const f=fixture();f.ui.openMarker('u03-quest');const key=f.ui.profileKey;assert.ok(f.ui.state.revision>0);f.profile={createdAt:'fictional-profile-b'};f.ui.ensure();assert.notEqual(f.ui.profileKey,key);assert.equal(f.ui.state.revision,0);assert.ok(f.values.has(key));});
test('damaged or future optional state remains stored and never blocks main-game access',()=>{const f=fixture(),key=B.STORAGE_KEY+':fictional-profile-a';f.values.set(key,'{bad');f.ui.ensure();assert.equal(f.ui.readOnly,true);assert.equal(f.values.get(key),'{bad');f.ui.openMarker('u03-quest');assert.equal(f.values.get(key),'{bad');assert.equal(f.writes.length,0);assert.match(f.messages[0],/主線仍可繼續/);});
function descendants(nodes){return nodes.flatMap(n=>[n,...descendants(n.children||[])]);}
test('requesting a puzzle hint preserves the unsubmitted draft in every control',()=>{const f=fixture();f.ui.openMarker('u03-quest');f.ui.puzzle('u03-evidence');let all=descendants(f.dialog.nodes),selects=all.filter(n=>n.tagName==='SELECT');selects[0].value='supported';selects[1].value='pending';all.find(n=>n.textContent==='需要一點提示').listeners.click();all=descendants(f.dialog.nodes);selects=all.filter(n=>n.tagName==='SELECT');assert.equal(selects[0].value,'supported');assert.equal(selects[1].value,'pending');assert.equal(f.ui.summary().progress['u03-evidence'].attempts,0);assert.equal(f.ui.summary().progress['u03-evidence'].hintsShown,1);});
test('optional story is not repeated when engine feedback returns the same narrative',()=>{const f=fixture();f.ui.openMarker('u03-quest');const story=C.getChapter('u03').markers.find(m=>m.id==='u03-quest').story;assert.equal(descendants(f.dialog.nodes).filter(n=>n.textContent===story).length,1);});
test('invalid ordering input shows feedback inside the modal and preserves its draft',()=>{const f=fixture();f.ui.openMarker('u03-handover-quest');f.ui.puzzle('u03-handover');const nodes=descendants(f.dialog.nodes),form=nodes.find(n=>n.tagName==='FORM'),card=C.getChapter('u03').puzzles.find(p=>p.id==='u03-handover').cards[0].id;nodes.filter(n=>n.tagName==='SELECT').forEach(n=>n.value=card);const before=f.ui.state.revision;form.listeners.submit({preventDefault(){}});assert.equal(f.ui.state.revision,before);const next=descendants(f.dialog.nodes),error=f.messages.at(-1);assert.ok(error);assert.ok(next.some(n=>n.textContent===error));assert.ok(next.filter(n=>n.tagName==='SELECT').every(n=>n.value===card));});
