'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const C=require('../js/tactical/tactical_classroom_client'),E=require('../js/tactical/tactical_engine'),S=require('../js/tactical/tactical_store'),B=require('../js/engine/rpg_bonus');
const NOW=Date.parse('2026-10-06T00:00:00.000Z'),CLASS='SYNTHETIC-CLASS-ONLY',A='synthetic-scope-aaaaaaaaaaaaaaaaaaaaaaaaaaaa',Z='synthetic-scope-bbbbbbbbbbbbbbbbbbbbbbbbbbbb',TOKEN='synthetic-private-token-00000000000000000001';
const clone=x=>JSON.parse(JSON.stringify(x));
function memory(){const values=new Map();return{values,fail:false,drop:false,getItem:k=>values.get(k)||null,setItem(k,v){if(this.fail)throw Error('QUOTA');if(!this.drop)values.set(k,v);}};}
function timer(){let t=NOW,n=0;const all=new Map();return{now:()=>t,setTimeout(fn,delay){all.set(++n,{fn,at:t+delay});return n;},clearTimeout(id){all.delete(id);},tick(ms){t+=ms;for(const [id,x]of all)if(x.at<=t){all.delete(id);x.fn();}}};}
const state=(more={})=>({classId:CLASS,queueScope:A,rankingsEnabled:true,expiresAt:new Date(NOW+3600000).toISOString(),connectionId:'a'.repeat(64),protocolVersion:2,engineVersion:'2.0.0',contentVersion:'tactical-2026-10-06-v1',bonusContentVersion:B.CONTENT_VERSION,...more});
const receipt=(id,more={})=>({ok:true,format:'ndmu-ethics-class-receipt',version:2,eventId:id,serverReceivedAt:new Date(NOW+1000).toISOString(),reviewStatus:'pending_teacher_review',duplicate:false,...more});
function store(storage=memory(),key=S.FORMAL_KEY){const s=new S({storage,key,lockManager:{request:(name,options,callback)=>{callback({name});return Promise.resolve();}}});s.saveProfile(s.loadProfile().data);return s;}
function finish(s){let battle=E.createState('u03');s.startAttempt(battle);while(battle.status==='active'){battle=E.command(battle,{type:'endTurn',revision:battle.revision}).state;s.saveSession(battle);}return s.finishAttempt(battle,{reason:'QA合成：界線與可靠交接。',revisionCondition:'QA合成：新需求時修正。'}).data;}
function rig(extra={}){const clock=timer(),storage=memory(),calls=[],changes=[];const options={mode:'public',enabled:true,Engine:E,Bonus:B,crypto:crypto.webcrypto,storage,now:clock.now,setTimeout:clock.setTimeout,clearTimeout:clock.clearTimeout,onChange:s=>changes.push(s),rpc:async(method,args)=>{calls.push({method,args:clone(args)});return receipt(JSON.parse(args[0]).eventId);},...extra};return{client:C.createClient(options),storage:options.storage,calls,changes,clock};}
function connect(r,s,st=state()){r.client.attachStore(s);r.client.connectBridge(st);r.client.setConsent(true);return r;}
const queue=c=>JSON.parse(c.exportQueue());
function payload(a){return{format:'ndmu-ethics-class-attempt',version:2,eventId:crypto.randomUUID(),classId:CLASS,attempt:a,bonus:B.exportEvents(B.createState())};}
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};}
function google(extra={}){const clock=timer(),calls=[],storage=memory(),handlers={beginClassroomLogin:()=>({ok:true,loginId:'synthetic-login-id-000000001',authUrl:'https://accounts.google.com/o/oauth2/v2/auth?state=synthetic',expiresAt:new Date(NOW+600000).toISOString()}),finishClassroomLogin:()=>({ok:true,status:'authenticated',sessionToken:TOKEN,expiresAt:new Date(NOW+3600000).toISOString(),classes:[{id:CLASS,label:'Synthetic class'}]}),classroomJoinTactical:id=>({ok:true,classId:id,queueScope:A,label:'Synthetic class',rankingsEnabled:true,bonusContentVersion:B.CONTENT_VERSION,protocolVersion:2,engineVersion:'2.0.0',contentVersion:'tactical-2026-10-06-v1'}),classroomSubmitTacticalAttempt:raw=>receipt(JSON.parse(raw).eventId),classroomTacticalLeaderboard:()=>[{nickname:'探索員 ABCD23',score:2,rank:1}],endClassroomLogin:()=>({ok:true})};const client=C.createClient({enabled:true,Engine:E,Bonus:B,crypto:crypto.webcrypto,storage,now:clock.now,rpc:async(m,args)=>{calls.push({m,args});return handlers[m](...args);},...extra});return{client,handlers,calls,storage,clock};}
async function login(g){await g.client.beginLogin();await g.client.pollLogin();await g.client.join(CLASS);g.client.setConsent(true);}

test('formal and preview stores keep separate keys, IDs and locks; legacy data untouched',()=>{const m=memory();m.values.set('ndmu-ethics-rpg:v1','legacy');const a=store(m),b=store(m,S.KEY);assert.notEqual(a.data.profileId,b.data.profileId);assert.ok(m.values.has(S.FORMAL_KEY));assert.ok(m.values.has(S.KEY));assert.equal(m.values.get('ndmu-ethics-rpg:v1'),'legacy');assert.throws(()=>store(m,'arbitrary'),/儲存空間/);});
test('v2 payload verifies actual immutable engine replay and exact completed reflection',()=>{const c=rig().client,a=finish(store()),p=payload(a);assert.equal(c.payloadValid(p),true);for(const mutation of [p=>p.version=1,p=>p.attempt.attemptId='old-id',p=>p.attempt.learning.reason=' ',p=>p.attempt.closedAt=new Date(NOW).toISOString(),p=>p.attempt.battle.units[0].hp=99,p=>p.attempt.battle.contentVersion='future',p=>p.attempt.extra=true,p=>p.email='not-allowed']){const bad=clone(p);mutation(bad);assert.throws(()=>c.payloadValid(bad));}});
test('v2 receipt rejects legacy, unknown fields, wrong event, malformed time and false success',()=>{const id=crypto.randomUUID(),r=receipt(id);assert.equal(C.validReceipt(r,id),true);for(const bad of [{...r,version:1},{...r,ok:false},{...r,sessionToken:TOKEN},{...r,eventId:crypto.randomUUID()},{...r,serverReceivedAt:'2026-10-06'}])assert.equal(C.validReceipt(bad,id),false);});
test('no capture or sending before both scoped connection and explicit local consent',async()=>{const r=rig(),s=store();finish(s);r.client.attachStore(s);r.client.capture();assert.equal(r.client.state().pending,0);r.client.connectBridge(state());r.client.capture();assert.equal(r.client.state().pending,0);assert.equal(await r.client.pump(),false);r.client.setConsent(true);assert.equal(r.client.state().pending,1);assert.equal(r.calls.length,0);});
test('capture uses stable round/terminal snapshots, never live reflection drafts or per-move traffic',()=>{const r=rig(),s=store();s.startAttempt(E.createState('u03'));connect(r,s);assert.equal(r.client.state().pending,0);let b=E.command(s.data.session.state,{type:'move',unitId:'guardian',x:2,y:2,revision:0}).state;s.saveSession(b);r.client.capture();assert.equal(r.client.state().pending,0);b=E.command(b,{type:'endTurn',revision:b.revision}).state;s.saveSession(b);r.client.capture();r.client.capture();assert.equal(r.client.state().pending,1);while(b.status==='active'){b=E.command(b,{type:'endTurn',revision:b.revision}).state;s.saveSession(b);}s.saveDraft(s.data.session.attemptId,{reason:'PRIVATE UNSENT DRAFT',revisionCondition:'draft'});r.client.capture();assert.equal(r.client.exportQueue().includes('PRIVATE UNSENT'),false);assert.equal(JSON.parse(queue(r.client).entries.at(-1).raw).attempt.learning,null);});
test('finished victory or loss is queued only with same replay-bound complete two-field reflection',()=>{const r=rig(),s=store();const a=finish(s);connect(r,s);const p=JSON.parse(queue(r.client).entries[0].raw);assert.deepEqual(p.attempt,a);assert.equal(p.version,2);assert.equal(p.attempt.battle.status,'lost');assert.equal(p.attempt.learning.reason,a.learning.reason);});
test('retry archives and synchronizes former complete command history without mixing new attempt',()=>{const r=rig(),s=store();let b=E.createState('u03');s.startAttempt(b);b=E.command(b,{type:'endTurn',revision:0}).state;s.saveSession(b);const id=s.data.session.attemptId;s.startAttempt(E.createState('u03'));connect(r,s);const p=JSON.parse(queue(r.client).entries[0].raw);assert.equal(p.attempt.attemptId,id);assert.equal(p.attempt.closure,'retry');assert.equal(p.attempt.battle.commandLog.length,1);assert.equal(p.attempt.learning,null);});
test('network retry keeps exact event ID and immutable bytes and requires a valid readback receipt',async()=>{let fail=true;const calls=[],r=rig({rpc:async(m,a)=>{calls.push({m,a:clone(a)});if(fail)throw Error('NETWORK');return receipt(JSON.parse(a[0]).eventId);}}),s=store();finish(s);connect(r,s);assert.equal(await r.client.pump(),false);fail=false;r.client.retry();assert.equal(await r.client.pump(),false);r.clock.tick(r.client.state().retryAfterMs);assert.equal(await r.client.pump(),true);assert.equal(calls[0].a[0],calls[1].a[0]);assert.equal(calls[0].m,'classroomSubmitTacticalAttempt');assert.equal(r.client.state().synced,1);const again=rig({storage:r.storage});again.client.attachStore(s);assert.equal(again.client.state().synced,1);});
test('legacy or invalid receipt never marks queued state synced',async()=>{const r=rig({rpc:async(m,a)=>receipt(JSON.parse(a[0]).eventId,{version:1})}),s=store();finish(s);connect(r,s);assert.equal(await r.client.pump(),false);assert.equal(r.client.state().pending,1);assert.equal(r.client.state().synced,0);});
test('consent revocation and account changes stop queued sends and preserve original owner',async()=>{const r=rig(),s=store();finish(s);connect(r,s);r.client.setConsent(false);assert.equal(await r.client.pump(),false);r.client.connectBridge(state({queueScope:Z,connectionId:'b'.repeat(64)}));assert.throws(()=>r.client.setConsent(true),/PROFILE_OWNER_CONFLICT/);assert.equal(await r.client.pump(),false);assert.equal(r.calls.length,0);assert.equal(r.client.state().foreignPending,1);});
test('import reset revokes consent without deleting queue or silently rebinding identities',()=>{const r=rig(),s=store();finish(s);connect(r,s);r.client.resetConsent('import');assert.equal(r.client.state().consent,false);assert.equal(r.client.state().pending,1);assert.equal(queue(r.client).owners[0].profile,s.data.profileId);});
test('write/readback failures fail closed before ownership consent or network',()=>{for(const field of ['fail','drop']){const m=memory();m[field]=true;const r=rig({storage:m}),s=store();finish(s);r.client.attachStore(s);r.client.connectBridge(state());assert.throws(()=>r.client.setConsent(true),/OWNERSHIP_STORAGE_REQUIRED/);assert.equal(r.client.state().consent,false);assert.equal(r.calls.length,0);}});
test('corrupted queue bytes remain exportable and cannot be overwritten or pumped',async()=>{const m=memory();m.values.set(C.STORAGE_KEY,'{bad');const r=rig({storage:m}),s=store();finish(s);r.client.attachStore(s);r.client.connectBridge(state());assert.throws(()=>r.client.setConsent(true));assert.equal(await r.client.pump(),false);assert.equal(m.values.get(C.STORAGE_KEY),'{bad');assert.equal(queue(r.client).damagedRaw,'{bad');});
test('preview store cannot be synchronized even if mistakenly passed into formal client',()=>{const r=rig(),s=store(memory(),S.KEY);finish(s);r.client.attachStore(s);r.client.connectBridge(state());assert.throws(()=>r.client.setConsent(true),/PREVIEW_STORE_PROHIBITED/);assert.equal(r.client.state().pending,0);});
test('v2 bridge state rejects unknown fields, v1 version, scope, expiry, source versions',()=>{for(const bad of [{...state(),protocolVersion:1},{...state(),token:TOKEN},{...state(),queueScope:'short'},{...state(),expiresAt:new Date(NOW).toISOString()},{...state(),engineVersion:'1.0'},{...state(),contentVersion:'next'}])assert.throws(()=>rig().client.connectBridge(bad),/BRIDGE_INVALID/);});
test('Google auth uses proof hash and never persists or publishes session credentials',async()=>{const g=google();await login(g);const commitment=g.calls.find(x=>x.m==='beginClassroomLogin').args[0],proof=g.calls.find(x=>x.m==='finishClassroomLogin').args[1];assert.equal(crypto.createHash('sha256').update(proof).digest('hex'),commitment);assert.equal(g.client.bridgeState().protocolVersion,2);assert.equal(g.calls.some(x=>x.m==='classroomJoinTactical'),true);for(const raw of [JSON.stringify(g.client.state()),g.client.exportQueue(),JSON.stringify(g.client.bridgeState())]){assert.equal(raw.includes(TOKEN),false);assert.equal(raw.includes(proof),false);}assert.equal(g.storage.values.size,0);g.client.logout();assert.equal(g.client.state().authenticated,false);});
test('Google v2 join refuses a legacy join response or changing supported versions',async()=>{const g=google();await g.client.beginLogin();await g.client.pollLogin();g.handlers.classroomJoinTactical=()=>({ok:true,classId:CLASS,queueScope:A,rankingsEnabled:true});await assert.rejects(g.client.join(CLASS),/JOIN_RESPONSE_INVALID/);assert.equal(g.client.bridgeState(),null);});
test('Google forward requires both consent, class and captured scope and verifies v2 receipt',async()=>{const g=google();await login(g);const raw=JSON.stringify(payload(finish(store())));await assert.rejects(g.client.submitRemote(raw,Z),/ACCESS_DENIED/);assert.equal((await g.client.submitRemote(raw,A)).version,2);g.client.setConsent(false);await assert.rejects(g.client.submitRemote(raw,A),/ACCESS_DENIED/);});
test('logout prevents late join promise from restoring stale identity',async()=>{const g=google();await g.client.beginLogin();await g.client.pollLogin();const pending=deferred(),old=g.handlers.classroomJoinTactical;g.handlers.classroomJoinTactical=()=>pending.promise;const work=g.client.join(CLASS);g.client.logout();pending.resolve(old(CLASS));await work;assert.equal(g.client.state().authenticated,false);assert.equal(g.client.bridgeState(),null);});
test('anonymous bonus leaderboards validate metric and row shape and reject late session results',async()=>{const g=google();await login(g);assert.equal((await g.client.leaderboard('puzzle'))[0].nickname,'探索員 ABCD23');await assert.rejects(g.client.leaderboard('victory'),/RANKINGS_DISABLED/);g.handlers.classroomTacticalLeaderboard=()=>[{nickname:'Real Name',score:2,rank:1}];await assert.rejects(g.client.leaderboard('puzzle'),/RANKINGS_RESPONSE_INVALID/);const wait=deferred();g.handlers.classroomTacticalLeaderboard=()=>wait.promise;const p=g.client.leaderboard('puzzle');g.client.logout();wait.resolve([]);await assert.rejects(p,/SESSION_CHANGED/);});

const makeClock = timer;
function fakeHost() {
  const timer = makeClock(), listeners = new Map(), intervals = new Map(), opened = [], sent = [];
  let serial = 0; const popup = { closed: false };
  const host = { crypto: crypto.webcrypto, popup, opened, sent, listeners, intervals, timer,
    setTimeout: timer.setTimeout, clearTimeout: timer.clearTimeout,
    setInterval(fn, delay) { const id = ++serial; intervals.set(id, { fn, delay }); return id; },
    clearInterval(id) { intervals.delete(id); },
    addEventListener(kind, fn) { if (!listeners.has(kind)) listeners.set(kind, []); listeners.get(kind).push(fn); },
    async emit(kind, event) { await Promise.all((listeners.get(kind) || []).map(fn => fn(event))); },
    open(...args) { opened.push(args); return popup; }
  };
  return host;
}
function transportRig(configExtra = {}) {
  const host = fakeHost(), states = [];
  const config = { enabled: true, endpoint: C.EXEC_ENDPOINT, bridgeOrigin: C.PINNED_BRIDGE_ORIGIN, ...configExtra };
  const transport = C.createBridgeTransport(host, config, state => states.push(state)); transport.open();
  const challenge = new URL(host.opened[0][0]).searchParams.get('bridge');
  const frame = { top: host.popup, postMessage: (data, origin) => host.sent.push({ data: clone(data), origin }) };
  const message = (type, extra = {}, override = {}) => host.emit('message', {
    origin: config.bridgeOrigin, source: frame, data: { protocol: C.BRIDGE_PROTOCOL, challenge, type, ...(type==='ready'?{capabilities:['verified-game-heartbeat-v1','safe-errors-v1'],heartbeatId:'e'.repeat(64)}:{}), ...extra }, ...override });
  return { host, states, config, transport, challenge, frame, message,
    async join(value = state()) { await message('ready'); await message('joined', { state:value }); } };
}
function serverRig(client, bootstrapExtra = {}) {
  const host = fakeHost(), sent = [];
  const opener = { postMessage: (data, origin) => sent.push({ data: clone(data), origin }) };
  host.top = { opener }; const challenge = 'c'.repeat(64);
  const server = C.installBridgeServer(host, client, { enabled: true, bridge: challenge, ...bootstrapExtra });
  const message = (type, extra = {}, override = {}) => host.emit('message', { origin: C.GAME_ORIGIN,
    source: opener, data: { protocol: C.BRIDGE_PROTOCOL, challenge, type, ...(type==='ready'?{capabilities:['verified-game-heartbeat-v1','safe-errors-v1'],heartbeatId:'e'.repeat(64)}:{}), ...extra }, ...override });
  return { host, sent, opener, challenge, server, message };
}
test('transport opens only fixed v2 mode with random nonce and never credentials',()=>{const t=transportRig(),url=new URL(t.host.opened[0][0]);assert.equal(url.searchParams.get('mode'),'tactical-classroom');assert.match(t.challenge,/^[a-f0-9]{64}$/);assert.equal(url.href.includes(TOKEN),false);assert.throws(()=>transportRig({endpoint:'https://evil.invalid'}),/BRIDGE_CONFIGURATION_INVALID/);assert.throws(()=>transportRig({enabled:false}),/CLASSROOM_DISABLED/);});
test('transport rejects wrong source, origin, challenge, protocol and unsupported joined versions',async()=>{const t=transportRig();for(const override of [{origin:'https://evil.invalid'},{source:{top:{}}},{data:{protocol:'ndmu-ethics-classroom-bridge-v1',challenge:t.challenge,type:'ready'}},{data:{protocol:C.BRIDGE_PROTOCOL,challenge:'b'.repeat(64),type:'ready'}}])await t.message('ready',{},override);await t.message('joined',{state:state()});assert.equal(t.states.at(-1),null);await t.message('ready');await t.message('joined',{state:state({protocolVersion:1})});assert.equal(t.states.at(-1),null);await t.message('joined',{state:state()});assert.equal(t.states.at(-1).protocolVersion,2);});
test('v2 transport RPC allowlist removes token and binds every request to the scoped nonce channel',async()=>{const t=transportRig();await t.join();await assert.rejects(t.transport.rpc('classroomSubmitAttempt',['',TOKEN,A]),/BRIDGE_CLOSED/);await assert.rejects(t.transport.rpc('classroomSubmitTacticalAttempt',['{}',TOKEN,Z]),/SESSION_CHANGED/);const p=t.transport.rpc('classroomSubmitTacticalAttempt',['{}',TOKEN,A]);const sent=t.host.sent.at(-1);assert.deepEqual(sent.data.args,['{}',A]);assert.equal(sent.origin,C.PINNED_BRIDGE_ORIGIN);assert.equal(JSON.stringify(sent).includes(TOKEN),false);await t.message('result',{requestId:sent.data.requestId,ok:true,result:{accepted:true}});assert.deepEqual(await p,{accepted:true});});
test('disconnect rejects in-flight requests and cannot accept a late result from former frame',async()=>{const t=transportRig();await t.join();const p=t.transport.rpc('classroomSubmitTacticalAttempt',['{}',TOKEN,A]);const rejection=assert.rejects(p,/BRIDGE_CLOSED/);const id=t.host.sent.at(-1).data.requestId;t.transport.disconnect();await rejection;await t.message('result',{requestId:id,ok:true,result:true});assert.equal(t.states.at(-1),null);});
test('v2 bridge server accepts only exact opener origin nonce and whitelisted RPC, never relays token',async()=>{const g=google();await login(g);const x=serverRig(g.client),raw=JSON.stringify(payload(finish(store()))),request={requestId:crypto.randomUUID(),method:'classroomSubmitTacticalAttempt',args:[raw,A]};const count=g.calls.length;await x.message('request',request,{origin:'https://evil.invalid'});await x.message('request',request,{source:{}});await x.message('request',request,{data:{protocol:'ndmu-ethics-classroom-bridge-v1',challenge:x.challenge,type:'request',...request}});assert.equal(g.calls.length,count);await x.message('request',request);assert.equal(g.calls.at(-1).m,'classroomSubmitTacticalAttempt');assert.equal(x.sent.at(-1).data.result.version,2);assert.equal(JSON.stringify(x.sent).includes(TOKEN),false);assert.equal(x.sent.at(-1).origin,C.GAME_ORIGIN);});
test('v2 server disconnect revokes consent/session and late requests cannot forward',async()=>{const g=google();await login(g);const x=serverRig(g.client);await x.message('disconnect');const count=g.calls.length;await x.message('request',{requestId:crypto.randomUUID(),method:'classroomSubmitTacticalAttempt',args:[JSON.stringify(payload(finish(store()))),A]});assert.equal(g.calls.length,count);assert.equal(g.client.state().authenticated,false);});
test('missing replay engine fails closed and cannot accept an apparently shaped forged battle',()=>{const c=C.createClient({enabled:true,mode:'public',crypto:crypto.webcrypto,Engine:undefined,Bonus:B}),p=payload(finish(store()));assert.throws(()=>c.payloadValid(p),/ATTEMPT_INVALID/);p.attempt.battle.units[0].hp=999;assert.throws(()=>c.payloadValid(p),/ATTEMPT_INVALID/);});
test('transmission validator rejects every nonempty draft even if terminal and server could parse it',async()=>{const g=google();await login(g);const a=finish(store()),b=clone(a);b.closure='in_progress';b.closedAt=null;b.learning=null;b.draft={reason:'UNSENT PRIVATE DRAFT',revisionCondition:''};await assert.rejects(g.client.submitRemote(JSON.stringify(payload(b)),A),/ATTEMPT_INVALID/);b.closure='retry';b.closedAt=a.closedAt;await assert.rejects(g.client.submitRemote(JSON.stringify(payload(b)),A),/ATTEMPT_INVALID/);assert.equal(g.calls.some(x=>x.m==='classroomSubmitTacticalAttempt'),false);});
test('classroom consent and pump require a confirmed exclusive writer lock, never non-atomic fallback',async()=>{for(const lockState of ['unsupported','pending','unavailable']){const r=rig(),s=store();finish(s);s.lockState=lockState;r.client.attachStore(s);r.client.connectBridge(state());assert.throws(()=>r.client.setConsent(true),/WRITE_LOCK_REQUIRED/);assert.equal(r.client.state().consent,false);assert.equal(await r.client.pump(),false);assert.equal(r.calls.length,0);}const r=rig(),s=store();finish(s);connect(r,s);s.lockState='unsupported';assert.equal(await r.client.pump(),false);assert.equal(r.calls.length,0);});
test('Google bridge lifecycle clears old requests, frees all slots and never publishes stale awaited results',async()=>{const g=google();await login(g);const x=serverRig(g.client),waits=[],args=[];g.handlers.classroomSubmitTacticalAttempt=raw=>{const d=deferred();waits.push(d);args.push(JSON.parse(raw));return d.promise;};const request=()=>({requestId:crypto.randomUUID(),method:'classroomSubmitTacticalAttempt',args:[JSON.stringify(payload(finish(store()))),A]});const old=request(),oldWork=x.message('request',old);await new Promise(r=>setImmediate(r));assert.equal(waits.length,1);await x.host.emit('pagehide',{persisted:true});await x.host.emit('pageshow',{persisted:true});await login(g);const next=[request(),request(),request()],work=next.map(r=>x.message('request',r));await new Promise(r=>setImmediate(r));assert.equal(waits.length,4,'old request must not occupy the three fresh request slots');waits[0].resolve(receipt(args[0].eventId));await oldWork;assert.equal(x.sent.some(s=>s.data.type==='result'&&s.data.requestId===old.requestId),false);for(let i=1;i<4;i++)waits[i].resolve(receipt(args[i].eventId));await Promise.all(work);assert.equal(x.sent.filter(s=>s.data.type==='result').length,3);});
