'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const Classroom=require('../js/tactical/tactical_classroom_client');
const html=fs.readFileSync('tactical/index.html','utf8');
const statusIds=['classroom-live-status','classroom-local-status','classroom-cloud-status','classroom-cloud-detail','classroom-cloud-counts','classroom-retry-countdown','classroom-status-action','classroom-sync-update','classroom-sync-error','completed-classroom-status'];
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.listeners={};this.attributes={};this.dataset={};this.children=[];this.innerHTML='';this.textContent='';this.value='';this.open=false;this.elements={};this.hidden=false;this.classList={toggle(){},contains(){return false;}};}
 addEventListener(t,fn){(this.listeners[t]||=[]).push(fn);}setAttribute(k,v){this.attributes[k]=v;}append(...v){this.children.push(...v);}prepend(v){this.children.unshift(v);}querySelector(){return null;}querySelectorAll(){return [];}contains(){return true;}closest(){return null;}focus(){}remove(){}showModal(){this.open=true;}close(){this.open=false;(this.listeners.close||[]).forEach(fn=>fn());}
}
function fixture(options={}){
 const nodes=new Map(['app','game-dialog','toast-region','voice-caption','save-warning','reflection-error','reflection-draft-status','reflection-form',...statusIds].map(id=>[id,new Element(id==='game-dialog'?'dialog':'div')]));
 const document={readyState:'loading',hidden:false,activeElement:null,body:new Element('body'),getElementById:id=>nodes.get(id),querySelectorAll:()=>[],createElement:tag=>new Element(tag),addEventListener(){}};
 const state={enabled:true,authenticated:false,consent:false,syncState:'disconnected',pending:0,synced:0,foreignPending:0,entries:[],retryAfterMs:0,message:'請先登入並同意同步。'},subscribers=new Set(),events={},intervals=new Map(),verifiedAttempts=new Map();let intervalId=0;
 const api={state:()=>state,hasReceiptForAttempt(attempt){return state.entries.some(e=>e.attemptId===attempt.attemptId&&e.closure==='finished'&&e.currentProfile===true&&e.currentScope===true&&e.status==='synced'&&Classroom.validReceipt(e.receipt,e.eventId)&&JSON.stringify(verifiedAttempts.get(e.eventId))===JSON.stringify(attempt));},subscribe(fn){subscribers.add(fn);return()=>subscribers.delete(fn);},capture(){},resetConsent(){state.consent=false;state.syncState='consent_required';},openPanel(){}};
 const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem(k,v){if(options.failSave)throw Error('quota');values.set(k,v);}};
 const context={document,localStorage:storage,TacticalRuntimeConfig:options.preview?undefined:{mode:'formal'},TacticalClassroomConfig:{enabled:true},TacticalClassroomClient:{validReceipt:Classroom.validReceipt,mountPublic:()=>api},navigator:{},console,crypto:require('node:crypto').webcrypto,Blob,TextEncoder,URL,Date,Math,scrollTo(){},addEventListener(t,fn){(events[t]||=[]).push(fn);},matchMedia:()=>({matches:false}),setTimeout(fn,ms){const timer=setTimeout(fn,ms<=600?0:ms);timer.unref?.();return timer;},clearTimeout,setInterval(fn){intervals.set(++intervalId,fn);return intervalId;},clearInterval(id){intervals.delete(id);}};
 context.window=context;context.globalThis=context;vm.createContext(context);for(const match of html.matchAll(/<script src="([^"]+)"/g)){const file=path.resolve('tactical',match[1]);vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});}
 const app=new context.TacticalGameApp.App();app.profile.settings.reducedMotion=true;return{app,api,state,nodes,document,events,intervals,subscribers,verifiedAttempts,emit(){for(const fn of subscribers)fn(state);}};
}
function complete(f){const {app,nodes}=f;app.start('u03');while(app.state.status==='active'){app.state=app.store.Engine.command(app.state,{type:'endTurn',revision:app.state.revision}).state;app.saveSession();}app.view='result';nodes.get('reflection-form').elements={reason:{value:'責任需要可靠交接。'},revisionCondition:{value:'若能力不足便尋求支援。'}};app.finishReflection();return app.finished.data;}
function entry(attemptId,extra={}){const eventId='11111111-2222-4333-8444-555555555555';return{attemptId,chapterId:'u03',closure:'finished',eventId,currentProfile:true,currentScope:true,status:'synced',receipt:{ok:true,format:'ndmu-ethics-class-receipt',version:2,eventId,serverReceivedAt:'2026-10-06T01:02:03.000Z',reviewStatus:'pending_teacher_review',duplicate:false},...extra};}
test('formal home, chapter, battle and result screens expose persistent separate local and cloud status',()=>{const f=fixture();assert.match(f.nodes.get('app').innerHTML,/id="classroom-live-status"/);assert.match(f.app.classroomStatusMarkup(),/本機等待首次儲存/);f.app.start('u03');assert.match(f.nodes.get('app').innerHTML,/本機已儲存/);assert.match(f.nodes.get('app').innerHTML,/尚未連接雲端/);f.app.navigate('chapters');assert.match(f.nodes.get('app').innerHTML,/id="classroom-live-status"/);complete(f);assert.match(f.nodes.get('app').innerHTML,/id="completed-classroom-status"/);assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);const preview=fixture({preview:true});assert.equal(preview.app.classroomStatusMarkup(),'');assert.equal(preview.subscribers.size,0);assert.equal(preview.intervals.size,0);});
test('storage failure cannot turn memory-only play into a saved local or received cloud status',()=>{const f=fixture({failSave:true});complete(f);assert.match(f.app.classroomStatusMarkup(),/本機尚未確認儲存/);assert.doesNotMatch(f.app.classroomStatusMarkup(),/本機已儲存/);assert.match(f.app.completedClassroomMarkup(),/反思暫留本頁記憶體/);assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);});
test('subscribed countdown updates leave game markup, focus and unsaved reflection inputs intact',()=>{const f=fixture();complete(f);const root=f.nodes.get('app'),before=root.innerHTML,form=f.nodes.get('reflection-form');f.document.activeElement=form.elements.reason;const focus=f.document.activeElement;Object.assign(f.state,{syncState:'waiting',authenticated:true,consent:true,retryAfterMs:12001,entries:[entry(f.app.finished.data.attemptId,{status:'pending',receipt:null})]});f.emit();assert.match(f.nodes.get('classroom-retry-countdown').textContent,/13 秒後自動重試/);f.state.retryAfterMs=8000;for(const tick of f.intervals.values())tick();assert.match(f.nodes.get('classroom-retry-countdown').textContent,/8 秒後自動重試/);assert.equal(root.innerHTML,before);assert.equal(f.document.activeElement,focus);assert.equal(form.elements.reason.value,'責任需要可靠交接。');assert.equal(f.subscribers.size,1);});
test('expired login, reconsent and profile conflicts remain actionable outside a dialog',()=>{const f=fixture();Object.assign(f.state,{syncState:'disconnected',message:'登入已到期，請重新登入同一帳號。'});f.emit();assert.equal(f.nodes.get('classroom-cloud-status').textContent,'雲端登入已到期');assert.match(f.nodes.get('classroom-cloud-detail').textContent,/登入原帳號/);assert.match(f.nodes.get('classroom-status-action').textContent,/連接班級同步/);Object.assign(f.state,{syncState:'consent_required',authenticated:true,message:'本機紀錄已變更，請再次核對帳號並同意同步。'});f.emit();assert.equal(f.nodes.get('classroom-cloud-status').textContent,'等待同步同意');assert.match(f.nodes.get('classroom-status-action').textContent,/核對並同意/);f.state.profileConflict=true;f.emit();assert.equal(f.nodes.get('classroom-sync-error').hidden,false);assert.match(f.nodes.get('classroom-sync-error').textContent,/另一帳號或班級/);assert.equal(f.nodes.get('game-dialog').open,false);});
test('only a verified finished receipt for the current exact attempt and profile marks the reflection received',()=>{const f=fixture(),attempt=complete(f);f.verifiedAttempts.set(entry(attempt.attemptId).eventId,JSON.parse(JSON.stringify(attempt)));Object.assign(f.state,{syncState:'synced',authenticated:true,consent:true});for(const invalid of [entry(attempt.attemptId,{closure:'in_progress'}),entry('different-attempt'),entry(attempt.attemptId,{currentProfile:false}),entry(attempt.attemptId,{currentScope:false}),entry(attempt.attemptId,{status:'pending'}),entry(attempt.attemptId,{receipt:{ok:true}})]){f.state.entries=[invalid];assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);}f.state.entries=[entry(attempt.attemptId,{closure:'in_progress'})];assert.equal(f.app.classroomStatus().title,'伺服器已收件');assert.match(f.app.completedClassroomMarkup(),/行動進度已收件不代表反思已收件/);f.state.entries.push(entry(attempt.attemptId));f.emit();assert.match(f.nodes.get('completed-classroom-status').innerHTML,/這一場完整學習紀錄：伺服器已收件/);assert.match(f.nodes.get('completed-classroom-status').innerHTML,/仍待教師核實，不自動算出席/);assert.doesNotMatch(f.app.classroomStatusMarkup()+f.app.completedClassroomMarkup(),new RegExp(attempt.attemptId));});
test('a generic synced state without a validated current receipt never asserts server receipt',()=>{const f=fixture();Object.assign(f.state,{syncState:'synced',synced:50,entries:[entry('old',{currentProfile:false})]});assert.doesNotMatch(f.app.classroomStatusMarkup(),/>伺服器已收件</);assert.match(f.app.classroomStatusMarkup(),/0 筆已收件/);});
test('late capture failure appears on the game page without undoing a save and a successful retry clears it',async()=>{const f=fixture();f.api.capture=()=>Promise.reject(Error('network'));f.app.start('u03');await Promise.resolve();assert.equal(f.app.store.persisted,true);assert.equal(f.nodes.get('classroom-sync-error').hidden,false);assert.match(f.nodes.get('classroom-sync-error').textContent,/班級同步暫時無法更新/);assert.equal(f.nodes.get('classroom-local-status').textContent,'本機已儲存');f.api.capture=()=>Promise.resolve();f.app.captureClassroom();await Promise.resolve();assert.equal(f.nodes.get('classroom-sync-error').hidden,true);});
test('pagehide and restored pages do not accumulate subscriptions or countdown timers',()=>{const f=fixture();assert.equal(f.intervals.size,1);assert.equal(f.subscribers.size,1);for(const hide of f.events.pagehide)hide();assert.equal(f.intervals.size,0);assert.equal(f.subscribers.size,0);for(const show of f.events.pageshow)show({persisted:true});for(const show of f.events.pageshow)show({persisted:true});assert.equal(f.intervals.size,1);assert.equal(f.subscribers.size,1);});
test('new sync status uses escaped text, does not reveal receipt IDs, and retains phone touch targets',()=>{const f=fixture();f.app.classroomError='<img src=x onerror=alert(1)>無法連線';assert.doesNotMatch(f.app.classroomStatusMarkup(),/<img src=x/);assert.match(f.app.classroomStatusMarkup(),/&lt;img/);const css=fs.readFileSync('css/tactical.css','utf8');assert.match(css,/\.classroom-live-status\{position:sticky;top:0/);assert.match(css,/\.sync-open\{min-height:44px/);assert.match(css,/@media\(max-width:680px\)\{\.classroom-live-status/);});
test('pending records remain counted after the current bridge scope disconnects',()=>{const f=fixture();f.state.entries=[entry('local-attempt',{status:'pending',receipt:null,currentScope:false})];f.state.foreignPending=1;assert.match(f.app.classroomStatusMarkup(),/1 筆待確認/);assert.match(f.app.classroomStatusMarkup(),/尚未連接雲端/);});
test('broken status subscription and cleanup cannot prevent local gameplay',()=>{const f=fixture();f.app.stopClassroomStatus();f.api.subscribe=()=>{throw Error('unavailable');};assert.doesNotThrow(()=>f.app.startClassroomStatus());f.app.start('u03');assert.equal(f.app.state.status,'active');f.app.classroomStatusUnsubscribe=()=>{throw Error('unavailable');};assert.doesNotThrow(()=>f.app.stopClassroomStatus());});

test('a restored same-ID attempt with changed reflection or completion timestamp cannot reuse an old receipt',()=>{const f=fixture(),attempt=complete(f),original=JSON.parse(JSON.stringify(attempt)),received=entry(attempt.attemptId);f.state.entries=[received];f.verifiedAttempts.set(received.eventId,original);assert.match(f.app.completedClassroomMarkup(),/這一場完整學習紀錄：伺服器已收件/);attempt.learning.reason='重新思考後採取不同的交接方式。';assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);attempt.learning.reason=original.learning.reason;attempt.closedAt='2026-10-06T08:08:08.000Z';attempt.learning.completedAt=attempt.closedAt;assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);f.app.finished.data=JSON.parse(JSON.stringify(original));assert.match(f.app.completedClassroomMarkup(),/這一場完整學習紀錄：伺服器已收件/);});
test('completion receipt requires the client exact-content helper and fails closed without an ID fallback',()=>{const f=fixture(),attempt=complete(f),received=entry(attempt.attemptId);f.state.entries=[received];f.verifiedAttempts.set(received.eventId,JSON.parse(JSON.stringify(attempt)));delete f.api.hasReceiptForAttempt;assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);f.api.hasReceiptForAttempt=()=>{throw Error('unavailable');};assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);f.api.hasReceiptForAttempt=()=>({ok:true});assert.match(f.app.completedClassroomMarkup(),/尚未確認雲端收件/);});
