'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const Engine=require('../js/tactical/tactical_engine'),Missions=require('../js/tactical/tactical_missions'),Renderer=require('../js/tactical/tactical_renderer');
const HTML=fs.readFileSync('tactical/index.html','utf8'),CSS=fs.readFileSync('css/tactical.css','utf8');
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.listeners={};this.attributes={};this.dataset={};this.children=[];this.innerHTML='';this.value='';this.open=false;this.elements={};this.classList={toggle(){},contains(){return false}};}
 addEventListener(type,fn){(this.listeners[type]||=[]).push(fn);}setAttribute(k,v){this.attributes[k]=v;}getAttribute(k){return this.attributes[k];}append(...children){this.children.push(...children);}prepend(child){this.children.unshift(child);}contains(){return true;}querySelector(){return null;}querySelectorAll(){return [];}focus(){}remove(){}click(){}showModal(){this.open=true;}close(){this.open=false;for(const fn of this.listeners.close||[])fn();}closest(){return null;}
}
function fixture(options={}){
 const nodes=new Map(['app','game-dialog','toast-region','save-warning','wardrobe-preview','reflection-error','reflection-form'].map(id=>[id,new Element(id==='game-dialog'?'dialog':'div')]));
 const listeners={},document={readyState:'loading',hidden:false,activeElement:null,body:new Element('body'),getElementById:id=>nodes.get(id),querySelectorAll:()=>[],createElement:tag=>new Element(tag),addEventListener:(t,fn)=>{(listeners[t]||=[]).push(fn);}};
 const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>{if(options.failSave)throw Error('quota');values.set(k,v)}};
 const context={document,localStorage:storage,navigator:{},console,crypto:require('node:crypto').webcrypto,Blob,TextEncoder,URL,Date,Math,Audio:options.Audio,scrollTo(){},addEventListener(){},matchMedia:()=>({matches:false}),setTimeout:(fn,ms)=>{const t=setTimeout(fn,ms<=600?0:ms);t.unref?.();return t;},clearTimeout, setInterval,clearInterval};context.window=context;context.globalThis=context;vm.createContext(context);
 for(const match of HTML.matchAll(/<script src="([^"]+)"/g)){const file=path.resolve('tactical',match[1]);vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});}
 const app=new context.TacticalGameApp.App();app.profile.settings.reducedMotion=true;return {context,app,nodes,values,document,listeners};
}
function terminal(app){app.start('u03');for(let i=0;i<20&&app.state.status==='active';i++){const result=app.store.Engine.command(app.state,{type:'endTurn',revision:app.state.revision});assert.equal(result.ok,true);app.state=result.state;app.saveSession();}assert.equal(app.state.status,'lost');app.view='result';app.render();return app.state;}
test('browser UMD scripts load in declared order and the complete app boots',()=>{const f=fixture();assert.equal(f.app.view,'home');assert.match(f.nodes.get('app').innerHTML,/每一步，都有人同行/);assert.equal(f.context.TacticalMissions.missions.length,13);assert.ok(f.app.store.loadBonus().data);assert.equal(f.nodes.get('app').attributes['aria-busy'],'false');});
test('isolated entry contains no auth, roster, collector or attendance wiring',()=>{for(const name of ['classroom_sync','receipt_client','classroom_config','rpg_store.js','rpg_app.js'])assert.ok(!HTML.includes(name),name);assert.ok(HTML.indexOf('rpg_bonus_content.js')<HTML.indexOf('engine/rpg_bonus.js'));assert.ok(HTML.indexOf('tactical_engine.js')<HTML.indexOf('tactical_store.js'));assert.ok(HTML.indexOf('tactical_renderer.js')<HTML.indexOf('tactical_app.js'));});
test('all thirteen chapters render and create playable revision-zero sessions',()=>{const f=fixture();for(const m of Missions.missions){f.app.briefing(m.id);assert.match(f.nodes.get('game-dialog').innerHTML,new RegExp(m.title));f.app.start(m.id,m.decisions[0].id);assert.equal(f.app.state.missionId,m.id);assert.equal(f.app.state.revision,0);assert.equal(f.app.state.status,'active');assert.ok(f.app.store.loadSession().data);assert.ok(f.nodes.get('app').innerHTML.includes('role="grid"'));}assert.ok(f.values.size===1);});
test('move is a reversible preview until explicit confirmation',async()=>{const {app}=fixture();app.start('u03');const start=app.state,target=Engine.reachable(start,'guardian')[0];app.tileClick(target.x,target.y);assert.equal(app.state,start);assert.equal(app.pending.command.type,'move');assert.equal(app.pending.preview.ok,true);app.pending=null;assert.equal(app.state.revision,0);app.tileClick(target.x,target.y);await app.execute(app.pending.command);assert.equal(app.state.revision,1);assert.equal(app.state.units[0].x,target.x);assert.equal(app.store.loadSession().data.revision,1);await app.execute({type:'undo',revision:app.state.revision});assert.equal(app.state.units[0].x,start.units[0].x);assert.equal(app.state.units[0].y,start.units[0].y);});
test('double action confirmation and stale revisions cannot repeat a move',async()=>{const {app}=fixture();app.start('u03');const target=Engine.reachable(app.state,'guardian')[0],command={type:'move',unitId:'guardian',x:target.x,y:target.y,revision:0};await app.execute(command);const revision=app.state.revision;await app.execute(command);assert.equal(app.state.revision,revision);});
test('guard only highlights the actor and creates a self-target preview',()=>{const {app}=fixture();app.start('u03');app.setMode('guard');assert.equal(app.pending.command.targetId,'guardian');assert.equal(app.uiData().targets.length,1);assert.ok(!app.actionbar(app.uiData()).includes('預計造成 0'));});
test('unspent moves prompt before endTurn and dialog cancel leaves state intact',()=>{const {app,nodes}=fixture();app.start('u03');app.endTurn();assert.equal(nodes.get('game-dialog').open,true);assert.match(nodes.get('game-dialog').innerHTML,/確認結束回合/);app.closeDialog();assert.equal(app.state.round,1);assert.equal(app.state.revision,0);});
test('enemy phase resets turn resources, saves state, and returns control',async()=>{const {app}=fixture();app.start('u03');await app.execute({type:'endTurn',revision:0});assert.equal(app.busy,false);assert.equal(app.enemyPhase,false);assert.equal(app.visualState,null);assert.equal(app.state.round,2);assert.equal(app.store.loadSession().data.round,2);});
test('new retry creates a new attempt from revision zero instead of reusing command revision',async()=>{const {app}=fixture();app.start('u03');await app.execute({type:'endTurn',revision:0});const old=app.store.data.session.attemptId;app.start(app.state.missionId,app.state.decisionId);assert.equal(app.state.revision,0);assert.equal(app.state.round,1);assert.notEqual(app.store.data.session.attemptId,old);assert.equal(app.store.loadAttempts().data.length,1);});
test('loss can complete two-column reflection and persisted status is explicit',()=>{const {app,nodes}=fixture();terminal(app);nodes.get('reflection-form').elements={reason:{value:'先確認能力界線與接手責任。'},revisionCondition:{value:'若支援窗口未回覆，就調整等待與交接安排。'}};app.finishReflection();assert.equal(app.finished.ok,true);assert.equal(app.finished.persisted,true);assert.equal(app.store.loadAttempts().data.at(-1).learning.reason,'先確認能力界線與接手責任。');assert.equal(app.store.loadSession().data,null);assert.match(nodes.get('app').innerHTML,/學習紀錄已儲存在此瀏覽器/);assert.match(nodes.get('app').innerHTML,/不等於正式成績或完成點名/);});
test('blank reflection keeps terminal session and directs focus to the missing field',()=>{const {app,nodes}=fixture();terminal(app);let focused=false;nodes.get('reflection-form').elements={reason:{value:'   ',focus(){focused=true}},revisionCondition:{value:'有新資訊才調整',focus(){}}};app.finishReflection();assert.equal(app.finished,null);assert.ok(app.store.loadSession().data);assert.equal(focused,true);assert.match(nodes.get('reflection-error').innerHTML,/兩欄都需要填寫/);});
test('unavailable storage never presents memory-only reflection as saved attendance',()=>{const {app,nodes}=fixture({failSave:true});terminal(app);nodes.get('reflection-form').elements={reason:{value:'責任需要可靠交接'},revisionCondition:{value:'若能力不足便求助'}};app.finishReflection();assert.equal(app.finished.ok,true);assert.equal(app.finished.persisted,false);assert.match(nodes.get('app').innerHTML,/反思暫留本頁，請下載備份/);assert.ok(!nodes.get('app').innerHTML.includes('學習紀錄已儲存在此瀏覽器'));});
test('wardrobe remains a draft on cancel, supports every catalog option and returns to illustration',()=>{const {app,nodes,context}=fixture();const original=JSON.stringify(app.profile.squadAppearance);app.wardrobe('scout');for(const key of Object.keys(context.RPGAvatar.catalog))assert.ok(nodes.get('game-dialog').innerHTML.includes('appearance-'+key));app.change({target:{dataset:{appearance:'hair'},value:'long'}});assert.equal(app.wardrobeModes.scout,'custom');assert.equal(JSON.stringify(app.profile.squadAppearance),original);app.closeDialog();app.wardrobe('scout');assert.equal(app.wardrobeModes.scout,'illustrated');assert.match(nodes.get('game-dialog').innerHTML,/精緻原型/);});
test('all optional chapter markers and all three puzzle kinds render without mutating combat',()=>{const {app,context,nodes}=fixture();app.start('u03');const before=JSON.stringify(app.state),kinds=new Set();for(const chapter of context.RPGBonusContent.chapters){app.bonus(chapter.id);for(const marker of chapter.markers){app.bonusMarker(marker.id);assert.equal(nodes.get('game-dialog').open,true);}for(const puzzle of chapter.puzzles){app.puzzle(puzzle.id);kinds.add(puzzle.kind);assert.match(nodes.get('game-dialog').innerHTML,/puzzle-form/);}}assert.equal(kinds.size,3);assert.equal(JSON.stringify(app.state),before);assert.ok(app.store.loadBonus().data.revision>0);});
test('sprite manifest references only existing approved files; fallback has no image network request',()=>{const {context}=fixture();const a=context.TacticalAssets;for(const group of [a.portraits,...Object.values(a.sprites)])for(const url of Object.values(group))assert.ok(fs.existsSync(path.resolve('tactical',url)),url);const defaultArt=Renderer.sprite('guardian',{},{});assert.ok(defaultArt.includes('<svg'));assert.ok(!defaultArt.includes('<img'));const art=Renderer.sprite('guardian',{},a);assert.match(art,/sprite-fallback/);assert.match(art,/guardian-idle\.png/);});
test('SVG and board labels escape unsafe strings without inline script handlers',()=>{const s=JSON.parse(JSON.stringify(Engine.createState('u03')));s.units[0].name='<img onerror=alert(1)>';const markup=Renderer.board(s,Missions.getMission('u03'),{selectedId:'guardian'});assert.ok(!markup.includes('<img onerror'));assert.match(markup,/&lt;img onerror=alert\(1\)&gt;/);assert.ok(!/\bon(?:click|load|error)=/.test(HTML));});
test('battle board provides one keyboard entry, semantic labels and visual threat legends',()=>{const s=Engine.createState('u03'),m=Missions.getMission('u03'),markup=Renderer.board(s,m,{focusCell:'1,2',selectedId:'guardian',intents:Engine.enemyIntents(s),showIntents:true});assert.equal((markup.match(/role="gridcell"/g)||[]).length,m.map.width*m.map.height);assert.equal((markup.match(/tabindex="0"/g)||[]).length,1);assert.match(markup,/aria-label="戰術地圖/);assert.match(markup,/生命/);assert.match(markup,/unit-enemy/);});
test('responsive controls, visible keyboard focus and reduced-motion fallbacks are present',()=>{assert.match(CSS,/@media\(max-width:680px\)/);assert.match(CSS,/:focus-visible/);assert.match(CSS,/prefers-reduced-motion/);assert.match(CSS,/min-height:44px/);assert.match(CSS,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);assert.match(CSS,/\.battle-mobile-objectives/);assert.match(HTML,/<dialog[^>]+aria-labelledby/);});
test('missing recorded voices are quiet and never request a fabricated file',()=>{let created=0;class Audio{constructor(){created++;}}const {app,context}=fixture({Audio});context.TacticalAssets={voices:{}};app.voice.play('guardian','select');assert.equal(created,0);assert.equal(app.voice.audio,null);});
test('recorded voice only plays supplied URL, throttles selection, restores BGM after error',async()=>{const audios=[];class Audio{constructor(url){this.url=url;this.events={};audios.push(this);}addEventListener(t,fn){this.events[t]=fn;}play(){return Promise.resolve();}pause(){this.paused=true;}}const {app,context}=fixture({Audio});context.TacticalAssets={voices:{guardian:{select:'../assets/tactical/voice/guardian-select.mp3',attack:'../assets/tactical/voice/guardian-attack.mp3'}}};const volumes=[];app.music={setVolume:v=>volumes.push(v)};app.voice.play('guardian','select');app.voice.play('guardian','select');assert.equal(audios.length,1);assert.equal(audios[0].url,'../assets/tactical/voice/guardian-select.mp3');audios[0].events.error();assert.equal(app.voice.audio,null);assert.equal(volumes.at(-1),app.profile.settings.musicVolume);app.voice.play('guardian','attack');assert.equal(audios.length,2);app.voice.stop();assert.equal(audios[1].paused,true);});
test('import preview requires explicit replacement and uses the store size limit',async()=>{const {app,nodes}=fixture();const old=app.store.data.profileId;await app.readImport({name:'example.json',size:10,text:async()=>'{"wrong":true}'});assert.match(nodes.get('game-dialog').innerHTML,/取代此瀏覽器/);assert.equal(app.store.data.profileId,old);app.confirmImport();assert.equal(app.store.data.profileId,old);assert.match(fs.readFileSync('js/tactical/tactical_app.js','utf8'),/file.size>root.TacticalStore.MAX_BYTES/);});

test('accepted command is saved before animation and interruption restores usable final state',async()=>{const {app}=fixture();app.start('u03');app.profile.settings.reducedMotion=false;const target=app.store.Engine.reachable(app.state,'guardian')[0];const promise=app.execute({type:'move',unitId:'guardian',x:target.x,y:target.y,revision:0});assert.equal(app.busy,true);assert.equal(app.store.loadSession().data.revision,1);assert.equal(app.state.revision,1);assert.ok(app.visualState);app.interruptAnimation();assert.equal(app.busy,false);assert.equal(app.visualState,null);assert.equal(app.state.units[0].x,target.x);await new Promise(resolve=>setTimeout(resolve,15));await promise;assert.equal(app.state.revision,1);assert.equal(app.busy,false);});
test('visibility interruption retains accepted enemy turn and recovery never repeats commands',async()=>{const {app,document,listeners}=fixture();app.start('u03');app.profile.settings.reducedMotion=false;const pending=app.execute({type:'endTurn',revision:0});assert.equal(app.store.loadSession().data.round,2);document.hidden=true;for(const fn of listeners.visibilitychange)fn();assert.equal(app.busy,false);assert.equal(app.state.round,2);document.hidden=false;for(const fn of listeners.visibilitychange)fn();assert.equal(app.state.commandLog.length,1);await new Promise(resolve=>setTimeout(resolve,15));await pending;assert.equal(app.state.commandLog.length,1);});
test('all chapter briefs expose concise ethical context and complete source-page clues',()=>{const {app,nodes}=fixture();for(const m of Missions.missions){app.briefing(m.id);assert.match(nodes.get('game-dialog').innerHTML,/這次討論什麼/);assert.ok(nodes.get('game-dialog').innerHTML.includes(Renderer.esc(m.ethicalContext)));app.start(m.id);app.notes();for(const concept of m.concepts)assert.ok(nodes.get('game-dialog').innerHTML.includes(Renderer.esc(concept.term)));for(const ref of m.sourceRefs)assert.ok(nodes.get('game-dialog').innerHTML.includes(ref.pages.join('、')));assert.ok(!/href=["'][^"']+\.pdf/.test(nodes.get('game-dialog').innerHTML));}assert.match(app.notice(),/正式上課入口/);});
test('imported attempts never inherit unsaved reflection text from the previous attempt',()=>{const source=fixture(),target=fixture();source.app.start('u01');while(source.app.state.status==='active'){source.app.state=source.app.store.Engine.command(source.app.state,{type:'endTurn',revision:source.app.state.revision}).state;source.app.saveSession();}terminal(target.app);target.app.reflection={reason:'舊局的特殊理由',revisionCondition:'舊局的修正条件'};target.app.pendingImport=source.app.store.exportJSON();target.app.confirmImport();assert.equal(target.app.reflection.reason,'');assert.equal(target.app.reflection.revisionCondition,'');assert.equal(target.app.finished,null);target.app.continue();assert.equal(target.app.state.missionId,'u01');assert.equal(target.app.reflection.reason,'');assert.ok(!target.nodes.get('app').innerHTML.includes('舊局的特殊理由'));assert.equal(target.app.reflectionAttemptId,target.app.store.loadSession().attemptId);});
test('same-attempt continue retains draft but a fresh attempt resets it',()=>{const {app}=fixture();terminal(app);app.reflection={reason:'同一局的理由',revisionCondition:'有支援才調整'};const id=app.store.loadSession().attemptId;app.navigate('home');app.continue();assert.equal(app.reflection.reason,'同一局的理由');assert.equal(app.reflectionAttemptId,id);app.start('u03');assert.notEqual(app.reflectionAttemptId,id);assert.equal(app.reflection.reason,'');});
test('real smoke and guarding states have visible overlays and descriptive cell labels',()=>{let s=Engine.createState('u03');s=Engine.command(s,{type:'skill',unitId:'scout',skillId:'smoke',x:2,y:3,revision:s.revision}).state;s=Engine.command(s,{type:'skill',unitId:'guardian',skillId:'guard',revision:s.revision}).state;const markup=Renderer.board(s,Missions.getMission('u03'));assert.equal((markup.match(/class="smoke-cloud"/g)||[]).length,s.smoke.length);assert.match(markup,/status-shield/);assert.match(markup,/掩護中，本回合減傷/);assert.match(markup,/煙幕中，本回合阻擋遠程視線/);});
test('environment hazards use mission schedules for present and next round, without hiding units',()=>{for(const m of Missions.missions){const s=Engine.createState(m.id),hazards=Engine.hazardCells(s),nextHazards=Engine.hazardCells(s,2),markup=Renderer.board(s,m,{hazards,nextHazards});const active=new Set(hazards.flatMap(h=>h.cells.map(p=>p.x+','+p.y)));assert.equal((markup.match(/class="hazard-warning"/g)||[]).length,active.size);if(hazards.length)assert.match(markup,/本回合結束環境警戒/);if(nextHazards.length&&!hazards.length)assert.match(markup,/下回合環境警戒預告/);assert.ok((markup.match(/data-unit=/g)||[]).length>=3);}});
test('every build, top and bottom choice changes actual SVG geometry or outfit details',()=>{for(const [key,values] of Object.entries({build:['regular','slim','broad'],top:['field','shirt','jacket','vest'],bottom:['straight','cargo','tapered']})){const outputs=values.map(value=>Renderer.avatarSVG('guardian',{[key]:value}));assert.equal(new Set(outputs).size,values.length,key);for(const output of outputs)assert.match(output,/<svg/);}assert.match(Renderer.avatarSVG('guardian',{build:'broad'}),/scale\(1\.13 1\)/);assert.match(Renderer.avatarSVG('guardian',{bottom:'cargo'}),/M30 101h13v10H30/);assert.match(Renderer.avatarSVG('guardian',{top:'jacket'}),/M52 66v29/);});
test('u03 UI action flow wins, saves every accepted operation, and completes learning reflection',async()=>{const {app,nodes}=fixture();app.start('u03');const route=[{type:'move',unitId:'scout',x:2,y:1},{type:'skill',unitId:'scout',skillId:'rescue',targetId:'civilian-1'},{type:'move',unitId:'guardian',x:3,y:3},{type:'skill',unitId:'guardian',skillId:'guard'},{type:'move',unitId:'medic',x:4,y:4},{type:'skill',unitId:'medic',skillId:'guard'},{type:'endTurn'},{type:'move',unitId:'scout',x:0,y:2},{type:'skill',unitId:'scout',skillId:'guard'},{type:'move',unitId:'guardian',x:5,y:3},{type:'skill',unitId:'guardian',skillId:'rescue',targetId:'civilian-2'},{type:'move',unitId:'medic',x:1,y:4},{type:'skill',unitId:'medic',skillId:'guard'},{type:'endTurn'},{type:'skill',unitId:'scout',skillId:'guard'},{type:'move',unitId:'guardian',x:2,y:3},{type:'skill',unitId:'guardian',skillId:'guard'},{type:'move',unitId:'medic',x:0,y:4},{type:'skill',unitId:'medic',skillId:'heal',targetId:'guardian'},{type:'endTurn'},{type:'skill',unitId:'scout',skillId:'guard'},{type:'move',unitId:'guardian',x:0,y:3}];for(const command of route){if(command.unitId)app.selectUnit(command.unitId);app.prepare(command);assert.ok(app.pending,JSON.stringify(command));await app.execute(app.pending.command);assert.equal(app.store.loadSession().data.revision,app.state.revision);}assert.equal(app.state.status,'won');assert.equal(app.state.metrics.rescued,2);assert.equal(app.view,'result');nodes.get('reflection-form').elements={reason:{value:'依能力界線先求助並建立交接。'},revisionCondition:{value:'若接手未確認就調整等待並回報限制。'}};app.finishReflection();assert.equal(app.finished.persisted,true);assert.equal(app.progress.completed.u03.count,1);});
test('out-of-bounds saved keyboard focus falls back to exactly one valid board cell',()=>{for(const m of Missions.missions){const markup=Renderer.board(Engine.createState(m.id),m,{focusCell:'99,99'});assert.equal((markup.match(/tabindex="0"/g)||[]).length,1);assert.match(markup,/data-cell="0,0" tabindex="0"/);assert.equal((markup.match(/role="row"/g)||[]).length,m.map.height);}});
test('continuing a smaller imported map resets focus inside its selected unit cell',()=>{const {app}=fixture();app.start('u01');app.focusCell='10,7';app.navigate('home');app.continue();const [x,y]=app.focusCell.split(',').map(Number);assert.ok(x<app.mission.map.width&&y<app.mission.map.height);assert.equal(x,app.selected.x);assert.equal(y,app.selected.y);});
