'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const Engine=require('../js/tactical/tactical_engine'),Missions=require('../js/tactical/tactical_missions'),Renderer=require('../js/tactical/tactical_renderer');
const HTML=fs.readFileSync('tactical/index.html','utf8'),CSS=fs.readFileSync('css/tactical.css','utf8');
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.listeners={};this.attributes={};this.dataset={};this.children=[];this.innerHTML='';this.value='';this.open=false;this.elements={};this.classList={toggle(){},contains(){return false}};}
 addEventListener(type,fn){(this.listeners[type]||=[]).push(fn);}setAttribute(k,v){this.attributes[k]=v;}getAttribute(k){return this.attributes[k];}append(...children){this.children.push(...children);}prepend(child){this.children.unshift(child);}contains(){return true;}querySelector(){return null;}querySelectorAll(){return [];}focus(){}remove(){}click(){}showModal(){this.open=true;}close(){this.open=false;for(const fn of this.listeners.close||[])fn();}closest(){return null;}
}
function fixture(options={}){
 const nodes=new Map(['app','game-dialog','toast-region','voice-caption','save-warning','wardrobe-preview','reflection-error','reflection-draft-status','reflection-form'].map(id=>[id,new Element(id==='game-dialog'?'dialog':'div')]));
 const listeners={},document={readyState:'loading',hidden:false,activeElement:null,body:new Element('body'),getElementById:id=>nodes.get(id),querySelectorAll:()=>[],createElement:tag=>new Element(tag),addEventListener:(t,fn)=>{(listeners[t]||=[]).push(fn);}};
 const values=options.values||new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>{if(options.failSave)throw Error('quota');values.set(k,v)}};
 const context={document,localStorage:storage,TacticalRuntimeConfig:options.runtimeConfig,TacticalClassroomConfig:options.classroomConfig,TacticalClassroomClient:options.classroomClient,navigator:{},console,crypto:require('node:crypto').webcrypto,Blob,TextEncoder,URL,Date:options.Date||Date,Math,Audio:options.Audio,scrollTo(){},addEventListener(){},matchMedia:()=>({matches:false}),setTimeout:(fn,ms)=>{const t=setTimeout(fn,ms<=600?0:ms);t.unref?.();return t;},clearTimeout, setInterval,clearInterval};context.window=context;context.globalThis=context;vm.createContext(context);
 for(const match of HTML.matchAll(/<script src="([^"]+)"/g)){const file=path.resolve('tactical',match[1]);vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});}
 const app=new context.TacticalGameApp.App();app.profile.settings.reducedMotion=true;return {context,app,nodes,values,document,listeners};
}

const Schedule=require('../js/data/course_schedule');
function clock(value){let current=Date.parse(value);class FixedDate extends Date{constructor(...args){super(...(args.length?args:[current]));}static now(){return current;}}return {Date:FixedDate,set(value){current=Date.parse(value);}};}
function formalAt(value){const time=clock(value),f=fixture({runtimeConfig:{mode:'formal'},Date:time.Date});return {...f,time};}
test('every chapter opens exactly at its Taipei class start and remains open indefinitely',()=>{for(const e of Object.values(Schedule.entries)){const n=Date.parse(e.opensAt);assert.equal(Schedule.isOpen(e.id,n-1),false);assert.equal(Schedule.isOpen(e.id,n),true);assert.equal(Schedule.isOpen(e.id,n+1),true);assert.equal(Schedule.isOpen(e.id,n+86400000*500),true);assert.equal(new Date(n).toISOString().slice(11,16),'05:30');}assert.equal(Schedule.entries.u07.opensAt,'2026-11-10T13:30:00+08:00');assert.equal(Schedule.isOpen('unknown',Date.now()),false);assert.equal(Schedule.isOpen('u01',NaN),false);});
test('formal cards show the opening date and all future direct starts and retries are gated',()=>{const f=formalAt('2026-10-06T13:30:00+08:00');assert.equal(f.app.chapterOpen('u03'),true);for(const m of Missions.missions.slice(3)){const before=f.app.store.exportJSON();f.app.briefing(m.id);assert.match(f.nodes.get('game-dialog').innerHTML,/本章尚未開放/);f.app.start(m.id);assert.equal(f.app.state,null);assert.equal(f.app.store.exportJSON(),before);assert.match(f.app.missionCard(m),/aria-disabled="true"/);assert.match(f.app.missionCard(m),/13:30（台北時間）/);}assert.doesNotMatch(f.app.missionCard(Missions.getMission('u03')),/aria-disabled="true"/);});
test('exact boundary permits the mission without midnight or closing-window shortcuts',()=>{const f=formalAt('2026-10-13T00:00:00+08:00');f.app.start('u04');assert.equal(f.app.state,null);f.time.set('2026-10-13T13:29:59.999+08:00');f.app.start('u04');assert.equal(f.app.state,null);f.time.set('2026-10-13T13:30:00+08:00');f.app.start('u04');assert.equal(f.app.state.missionId,'u04');f.time.set('2026-12-30T23:00:00+08:00');f.app.start('u04');assert.equal(f.app.state.missionId,'u04');});
test('old future session/import is retained but cannot resume or create a new attempt before opening',()=>{const f=formalAt('2026-12-23T13:30:00+08:00');f.app.start('u13');const original=f.app.store.exportJSON(),id=f.app.store.loadSession().attemptId;f.time.set('2026-10-06T13:30:00+08:00');f.app.navigate('home');f.app.continue();assert.equal(f.app.view,'home');assert.equal(f.app.store.exportJSON(),original);f.app.start('u13');assert.equal(f.app.store.loadSession().attemptId,id);const imported=formalAt('2026-10-06T13:30:00+08:00');imported.app.pendingImport=original;imported.app.confirmImport();const saved=imported.app.store.exportJSON();imported.app.continue();assert.equal(imported.app.view,'home');assert.equal(imported.app.store.exportJSON(),saved);});
test('future bonus entry, marker, hint and answer are gated without losing historical bonus records',()=>{const f=formalAt('2026-10-06T13:30:00+08:00');const before=f.app.store.exportJSON();f.app.bonus('u13');assert.match(f.nodes.get('game-dialog').innerHTML,/本章尚未開放/);f.app.bonusChapter='u13';f.app.bonusMarker('made-up');f.app.puzzleAnswer(true);f.app.puzzleAnswer(false);assert.equal(f.app.store.exportJSON(),before);});
test('preview remains independent and formal missing schedule fails closed',()=>{const f=fixture({Date:clock('2026-09-01T00:00:00+08:00').Date});f.app.start('u13');assert.equal(f.app.state.missionId,'u13');const formal=formalAt('2026-12-23T00:00:00+08:00');formal.context.CourseSchedule=undefined;formal.app.start('u01');assert.equal(formal.app.state,null);assert.match(formal.nodes.get('game-dialog').innerHTML,/開放時間待確認/);});
test('an open chapter page refreshes at the next exact opening without touching saved progress',()=>{const f=formalAt('2026-10-13T13:29:59.999+08:00'),scheduled=[];f.context.setTimeout=(fn,ms)=>{scheduled.push({fn,ms});return 0;};f.app.navigate('chapters');const before=f.app.store.exportJSON();f.app.scheduleOpeningRefresh();assert.equal(scheduled[0].ms,1);assert.match(f.app.missionCard(Missions.getMission('u04')),/aria-disabled/);f.time.set('2026-10-13T13:30:00+08:00');scheduled[0].fn();assert.doesNotMatch(f.app.missionCard(Missions.getMission('u04')),/aria-disabled/);assert.equal(f.app.store.exportJSON(),before);assert.equal(scheduled[1].ms,7*24*60*60*1000);});
