'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),X=require('../legacy-v1/js/legacy_queue_export');
const now='2026-10-06T00:00:00.000Z',id='aaaaaaaa-aaaa-4aaa-8aaa-000000000001';
function valid(){return {format:'ndmu-ethics-classroom-queue',version:2,owners:[{profile:'synthetic-profile',queueScope:'synthetic-scope'}],entries:[{eventId:id,classId:'synthetic-class',queueScope:'synthetic-scope',lineage:'synthetic-lineage',raw:JSON.stringify({format:'ndmu-ethics-class-attempt',version:1,eventId:id,classId:'synthetic-class',attempt:{chapterId:'u03'},bonus:null}),status:'pending',receipt:null,tries:0,nextTryAt:0,error:''}]};}
test('no queue gives an honest empty notice without manufacturing a file or receipt',()=>{const x=X.backup(null,now);assert.equal(x.text,null);assert.equal(x.validation.status,'empty');assert.match(x.validation.message,/沒有舊待同步/);});
test('valid queue is structure-checked, wrapped losslessly and uses a filename without PII',()=>{const raw=JSON.stringify(valid(),null,3),x=X.backup(raw,now),decoded=JSON.parse(x.text);assert.equal(x.validation.status,'structure-checked');assert.equal(x.validation.events,1);assert.equal(decoded.raw,raw);assert.equal(decoded.storageKey,X.KEY);assert.equal(decoded.clockSource,'device-untrusted');assert.equal(x.fileName,'國醫軍事倫理冒險-舊待同步備援-20261006.json');});
test('broken JSON and unsafe-looking text are never evaluated or repaired, including lone surrogates',()=>{for(const raw of ['','{bad','<script>alert(1)</script>','bad\ud800text']){const x=X.backup(raw,now);assert.equal(x.validation.status,'unverified');assert.equal(JSON.parse(x.text).raw,raw);}});
test('oversized queue skips parsing and retains every character rather than silently truncating',()=>{const raw='x'.repeat(X.MAX_PARSE_CHARS+1),x=X.backup(raw,now);assert.equal(x.validation.status,'unverified');assert.match(x.validation.message,/較大/);assert.equal(JSON.parse(x.text).raw,raw);});
test('malformed metadata and newer-version queues remain recoverable but never claim valid structure',()=>{for(const q of [{...valid(),version:99},{...valid(),email:'synthetic@example.invalid'},{...valid(),entries:[{unexpected:true}]}]){const raw=JSON.stringify(q),x=X.backup(raw,now);assert.equal(x.validation.status,'unverified');assert.equal(JSON.parse(x.text).raw,raw);}});
test('user download reads only original key and leaves storage bytes unchanged',()=>{const raw=JSON.stringify(valid()),listeners={},status={textContent:''},downloads=[],urls=[],reads=[];const button={addEventListener:(k,f)=>listeners[k]=f},body={append:a=>downloads.push(a)},doc={body,getElementById:id=>id==='legacy-queue-export'?button:status,createElement:()=>({click(){this.clicked=true;},remove(){this.removed=true;}})},host={localStorage:{getItem:key=>{reads.push(key);return raw;},setItem(){throw Error('MUST_NOT_WRITE');},removeItem(){throw Error('MUST_NOT_DELETE');}},Blob:class{constructor(parts){this.parts=parts;}},URL:{createObjectURL:blob=>{urls.push(blob);return 'blob:synthetic';},revokeObjectURL(){}},setTimeout:fn=>fn()};X.mount(doc,host);listeners.click();assert.deepEqual(reads,[X.KEY]);assert.equal(JSON.parse(urls[0].parts[0]).raw,raw);assert.equal(downloads[0].clicked,true);assert.equal(downloads[0].removed,true);assert.match(status.textContent,/本機下載/);});
test('read failures are explained without downloads and script has no sync, network or storage mutation API',()=>{let clicked;const status={},doc={getElementById:id=>id==='legacy-queue-export'?{addEventListener:(k,f)=>clicked=f}:status},host={get localStorage(){throw Error('DENIED');}};X.mount(doc,host);clicked();assert.match(status.textContent,/沒有變更/);const source=fs.readFileSync('legacy-v1/js/legacy_queue_export.js','utf8');assert.ok(!/\b(?:fetch|XMLHttpRequest|WebSocket|sendBeacon|eval|Function|setItem|removeItem)\s*\(/.test(source));assert.ok(!/postMessage|script\.google|classroomSubmit/.test(source));});
