'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const avatarPreview=process.argv.includes('--avatar');
const savePrefix=avatarPreview?'ndmu-ethics-rpg-avatar-preview':'ndmu-ethics-rpg-preview';
const outboxKey=avatarPreview?'ndmu-ethics-classroom-avatar-preview-outbox:v1':'ndmu-ethics-classroom-preview-outbox:v1';
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const image='data:image/webp;base64,'+fs.readFileSync(path.join(root,'assets/rpg/training-base.webp')).toString('base64');
const portraits=Object.fromEntries(['cadet','liaison','logistics','doctor'].map(key=>[key,'data:image/webp;base64,'+fs.readFileSync(path.join(root,'assets/rpg/portrait-'+key+'.webp')).toString('base64')]));
const effects=Object.fromEntries(['menu','confirm','clue'].map(key=>[key,'data:audio/mpeg;base64,'+fs.readFileSync(path.join(root,'assets/audio/'+key+'.mp3')).toString('base64')]));
html=html.replace(/<link rel="stylesheet" href="([^"]+)">/g,(_,file)=>'<style>'+fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n').replace("url('../assets/rpg/training-base.webp')",`url('${image}')`)+'</style>');
const scripts=[];
html=html.replace(/<script defer src="([^"]+)"><\/script>/g,(_,file)=>{if(file==='js/classroom_sync_client.js'||file==='js/classroom_sync_boot.js')return '';let source=fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n');if(file==='js/classroom_config.js'){source=`window.ClassroomConfig={enabled:false,collectorUrl:'',sessionId:'',assignedChapter:'',sessionLabel:'',privacyUrl:'../../privacy.html'};`;}if(file==='js/classroom_sync_config.js'){source=`window.ClassroomSyncConfig={enabled:false,endpoint:'',bridgeOrigin:''};`;}source=source.replaceAll('ndmu-ethics-classroom:queue:v1',savePrefix+':classroom-queue:v1').replaceAll("'ndmu-ethics-rpg:v1'","'"+savePrefix+":v1'").replaceAll("'ndmu-ethics-classroom-outbox:v1'","'"+outboxKey+"'").replaceAll('ndmu-ethics-rpg:avatar:v1',savePrefix+':avatar:v1').replaceAll('ndmu-ethics-rpg:bonus:v1',savePrefix+':bonus:v1');scripts.push('<script>'+source.replaceAll('</script','<\\/script')+'</script>');return''});
html=html.replace('</body>',`<script>window.RPG_PORTRAIT_ASSETS=${JSON.stringify(portraits)};window.RPG_EFFECT_ASSETS=${JSON.stringify(effects)};</script>`+scripts.join('\n')+'</body>');
if(avatarPreview)html=html.replace('<body>','<body><div style="padding:10px 16px;background:#e9ce85;color:#243d36;text-align:center;font:600 13px sans-serif" role="note">角色與配樂預覽 · 收件已關閉 · <a href="../../" style="color:#243d36;text-decoration:underline">回正式上課遊戲</a></div>');
html=html.replaceAll('href="privacy.html"','href="../../privacy.html"').replaceAll('href="favicon.svg"','href="../../favicon.svg"');
const out=path.join(root,avatarPreview?'preview/avatar-audio/index.html':'preview/u03/index.html');fs.mkdirSync(path.dirname(out),{recursive:true});html=html.replace(/^[ \t]+$/gm,'');fs.writeFileSync(out,html);console.log({path:out,bytes:Buffer.byteLength(html)});
